### ISSUE TITLE
custom-gallery.patch needs to be updated for 1.74.0

### ISSUE THREAD

**Issue by brjsp** [VSCodium/vscodium#1349]
When trying to build vscode 1.74.0 on linux with custom-gallery.patch from your repo, i am getting the following error:
```
[  337s] [10:48:31] Using gulpfile ~/rpmbuild/BUILD/vscode-1.74.0/gulpfile.js
[  337s] [10:48:31] Starting 'vscode-linux-x64-min'...
[  337s] [10:48:31] Starting [36mclean-out-build[39m ...
[  337s] [10:48:31] Finished [36mclean-out-build[39m after [35m3 ms[39m
[  337s] [10:48:31] Starting [36mbuild-web-node-paths[39m ...
[  337s] [10:48:31] Finished [36mbuild-web-node-paths[39m after [35m4 ms[39m
[  337s] [10:48:31] Starting [36mcompile-api-proposal-names[39m ...
[  337s] [10:48:31] Starting [32mcompilation[39m[34m api-proposal-names[39m...
[  338s] [10:48:31] Finished [32mcompilation[39m[34m api-proposal-names[39m with 0 errors after [35m72 ms[39m
[  338s] [10:48:31] Finished [36mcompile-api-proposal-names[39m after [35m84 ms[39m
[  338s] [10:48:31] Starting [36m<anonymous>[39m ...
[  568s] [10:52:22] Starting [32mcompilation[39m...
[ 1103s] [11:01:17] [31mError[39m: /home/abuild/rpmbuild/BUILD/vscode-1.74.0/src/vs/platform/product/common/product.ts(32,54): Property 'recommendationsUrl' does not exist on type '{ readonly serviceUrl: string; readonly servicePPEUrl?: string | undefined; readonly searchUrl?: string | undefined; readonly itemUrl: string; readonly publisherUrl: string; readonly resourceUrlTemplate: string; readonly controlUrl: string; readonly nlsBaseUrl: string; } | {}'.
[ 1103s] [11:01:17] [31mError[39m: /home/abuild/rpmbuild/BUILD/vscode-1.74.0/src/vs/platform/product/common/product.ts(64,48): Cannot find name 'FileAccess'.
[ 1103s] [11:01:17] Finished [32mcompilation[39m with 2 errors after [35m535116 ms[39m
[ 1103s] [11:01:17] [31mError[39m: /home/abuild/rpmbuild/BUILD/vscode-1.74.0/src/vs/platform/product/common/product.ts(32,54): Property 'recommendationsUrl' does not exist on type '{ readonly serviceUrl: string; readonly servicePPEUrl?: string | undefined; readonly searchUrl?: string | undefined; readonly itemUrl: string; readonly publisherUrl: string; readonly resourceUrlTemplate: string; readonly controlUrl: string; readonly nlsBaseUrl: string; } | {}'.
[ 1103s] [11:01:17] [31mError[39m: /home/abuild/rpmbuild/BUILD/vscode-1.74.0/src/vs/platform/product/common/product.ts(64,48): Cannot find name 'FileAccess'.
[ 1103s] [11:01:17] Finished [32mcompilation[39m with 2 errors after [35m535118 ms[39m
[ 1103s] [11:01:17] 'vscode-linux-x64-min' errored after 13 min
[ 1103s] [11:01:17] Error: Found 2 errors
[ 1103s]     at Stream.<anonymous> (/home/abuild/rpmbuild/BUILD/vscode-1.74.0/build/lib/reporter.js:92:29)
[ 1103s]     at _end (/home/abuild/rpmbuild/BUILD/vscode-1.74.0/node_modules/through/index.js:65:9)
[ 1103s]     at stream.end (/home/abuild/rpmbuild/BUILD/vscode-1.74.0/node_modules/through/index.js:74:5)
[ 1103s]     at Stream.onend (node:internal/streams/legacy:47:10)
[ 1103s]     at Stream.emit (node:events:525:35)
[ 1103s]     at Stream.emit (node:domain:552:15)
[ 1103s]     at drain (/home/abuild/rpmbuild/BUILD/vscode-1.74.0/node_modules/through/index.js:34:23)
[ 1103s]     at stream.resume (/home/abuild/rpmbuild/BUILD/vscode-1.74.0/node_modules/through/index.js:99:5)
[ 1103s]     at Stream.ondrain (node:internal/streams/legacy:29:14)
[ 1103s]     at Stream.emit (node:events:513:28)
[ 1104s] error Command failed with exit code 1.
```
1.73.1 worked fine.

**Comment by daiyam** [comment]
it's in the insider branch...
