### ISSUE TITLE
The editor could not be opened due to an unexpected error: Failed to fetch

### ISSUE THREAD

**Issue by abhemanyus** [VSCodium/vscodium#1379]
Type: <b>Bug</b>

After a random amount of time has passed, the current opened tab is replaced with the following message:
"The editor could not be opened due to an unexpected error: Failed to fetch"

VSCodium version: VSCodium - Insiders 1.75.0-insider (9034d45b2d0168e5819375a2570c406a203df907, 2023-01-17T08:20:25.369Z)
OS version: Linux x64 5.15.0-58-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics (4 x 2325)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|13.58GB (9.98GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by icebarf** [comment]
Facing the same error/bug as above user, here a few additional logs.

<details>
<summary>Window Logs</summary>
<br>
```
2023-01-20 08:26:48.382 [error] TypeError: Failed to fetch
    at Nc.ec (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:99510)
    at Nc.cc (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:95383)
    at Nc.setInput (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:85988)
    at async n.H (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2469:5097)
    at async n.y (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2469:3926)
    at async n.openEditor (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2469:3041)
    at async vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2680:13506
2023-01-20 08:26:48.587 [error] Failed to fetch: TypeError: Failed to fetch
    at Nc.ec (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:99510)
    at Nc.cc (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:95383)
    at vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:84021
    at u.queue (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:89:12754)
    at je (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:84006)
    at vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:85649
    at u.invoke (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at s.deliver (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at d.fire (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at Q (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:550:791)
    at T.s (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:550:1576)
    at T.r (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:550:1470)
    at vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:549:1347
    at u.invoke (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at s.deliver (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at d.fire (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at EventEmitter.ae (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:83:25906)
    at EventEmitter.emit (node:events:526:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:755)
2023-01-20 08:26:49.752 [info] [perf] Render performance baseline is 197ms
2023-01-20 08:27:08.480 [error] Failed to fetch: TypeError: Failed to fetch
    at Nc.ec (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:99510)
    at Nc.cc (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:95383)
    at vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:84021
    at u.queue (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:89:12754)
    at $ (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:89:12608)
2023-01-20 08:32:10.731 [info] [perf] Render performance baseline is 177ms
2023-01-20 08:33:23.122 [warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
2023-01-20 08:35:04.529 [error] ENOENT: no such file or directory, open '/home/ice/.config/VSCodium/User/globalStorage/vscodevim.vim/.registers': Error: ENOENT: no such file or directory, open '/home/ice/.config/VSCodium/User/globalStorage/vscodevim.vim/.registers'
2023-01-20 08:36:05.721 [error] TypeError: Failed to fetch
    at Nc.ec (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:99510)
    at Nc.cc (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:95383)
    at Nc.setInput (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:85988)
    at async n.H (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2469:5097)
    at async n.y (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2469:3926)
    at async n.openEditor (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2469:3041)
    at async vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2680:13506
2023-01-20 08:36:07.337 [error] Failed to fetch: TypeError: Failed to fetch
    at Nc.ec (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:99510)
    at Nc.cc (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:95383)
    at vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:84021
    at u.queue (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:89:12754)
    at je (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2761:84006)
    at u.invoke (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at s.deliver (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at d.fire (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2034:24753
    at async Promise.all (index 0)
    at async N.Q (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2034:22649)
    at async Promise.all (index 0)
    at async u.a (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2034:19521)
```
</details>

**Comment by vvorrn** [comment]
VSCodium.x64.1.73.1.22314.dmg  also has this error

**Comment by spignelon** [comment]
![image](https://user-images.githubusercontent.com/92091338/229587373-2509c9db-4b89-406d-8cb4-36ed06eb93d0.png)
Same error, reinstalled, and deleted the .vscode-oss data. The issue persists
