### ISSUE TITLE
GitHub Copilot, Copilot Chat and Copilot Labs Extensions Not Working in VSCodium

### ISSUE THREAD

**Issue by Tushar49** [VSCodium/vscodium#1546]
**Describe the bug**
I am having trouble integrating GitHub Copilot and Copilot Labs extensions with VSCodium. Despite having access to GitHub Copilot X, I am unable to get it working with VSCodium. The Copilot Labs extension isn't working and the Copilot chat doesn't show up in the activity bar.

**Please confirm that you have searched existing issues in the repo.**
Yes, I have searched existing issues.

**Please confirm that you have checked the [FAQs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md).**
Yes, I have checked the FAQs.

**VSCodium version**
Version: 1.79.0 (system setup)
Release: 23159
Commit: 4be06ce527f2ea3b9b3096ac4b4c5aa11c64e7a4
Date: 2023-06-08T21:27:43.604Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**To Reproduce**
1. Install VSCodium and the GitHub Copilot extension.
2. Attempt to authenticate the GitHub Copilot extension.
3. Receive error: "Invalid copilot token: missing token: 404" and "GitHub Copilot could not connect to server. Extension activation failed: "User not authorized".
4. Install and attempt to authenticate the Copilot Labs extension.
5. Receive error: "Something went wrong. Please check that the main GitHub Copilot extension is installed and running and try again." and "Something went wrong checking access: Authentication error: NotAuthorized".

**Expected behavior**
I expect to be able to use GitHub Copilot and Copilot Labs extensions with VSCodium without any issues.

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Architecture: x64
 - Version: 10.0.22621

**Additional context**
I have tried several troubleshooting steps, including signing in and out of GitHub Copilot, editing the product.json file, and generating a new personal access token. None of these steps have resolved the issue.

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/discussions/1487

**Comment by Tushar49** [comment]
I have given a try to the steps mentioned in that issue as well, but it only deals with CoPilot Nightly extension issue, and not the Copilot labs as well as Copilot chat issues.

**Comment by gabrielrotbart** [comment]
+1
Have had copilot work flawlessly using the steps above for some months, but now that I have access to Chats it's not showing up in the activity bar even though it does in Vscode (re-installed for the first time in a long time just to test it out 😔) and the following inline commands are not showing up either:
- Copilot generate
- Copilot explain

Appreciate all you do maintainers. Could be that we just accept the trade off?

**Comment by GitMensch** [comment]
Is this something we could help with in VSCodium at all - or should we just link the discussion issue in the wiki and close this issue?

**Comment by Tushar49** [comment]
This is an issue that Copilot chat oesnt work

**Comment by GitMensch** [comment]
The issue is that this extension is both proprietary and closed-source and only "blesses" the MS binaries; the question is therefore: can we do anything about this in vscodium _directly_ - like adjusting the distributed product.json?

If not then the discussion issue seems to be a better place to check what/how something works and to document the result in the wiki - like we do for other MS extensions - or place a link to the discussion there.

The _real solution_ to this issue would be of course that the extension is made public and under a free license (even if the endpoint needs online access which is stored behind an access token) and does not need any "blessing"but work on the OSS version of vscode out-of-the-box.
But that's to be requested in the Copilot issue tracker and/or the vscode repo.

**Comment by wtf403** [comment]
Yes, it's possible to make Copilot Chat work by tweaking some lines in the product.json file. However, I haven't managed to do this for the VScode Figma extension🥲 We definitely need someone to explain what's going on in the product.json file.

**Comment by movq** [comment]
> Yes, it's possible to make Copilot Chat work by tweaking some lines in the product.json file.

@wtf403 Would you mind sharing what tweaks are needed to get this working? I'm using VSCodium Insider, and have the Copilot Chat extension installed. Regular Copilot features work but Chat doesn't. The extension logs for Copilot Chat say
```
[INFO] [auth] [2023-07-05T16:11:08.579Z] GitHub login failed
[ERROR] [default] [2023-07-05T16:11:08.583Z] You are not signed in to GitHub. Please sign in to use Copilot.
```
even though I am definitely logged in (since regular Copilot works).

**Comment by mkiselev** [comment]
Sorry, for now, I can't 🙃
I recently reinstalled VSCodium and overwrote the product.json file. After that, the student subscription on connected GitHub account expired🤣 Currently i'm in Copilot Chat waitlist. Not sure how to make it work again.

**Comment by wtf403** [comment]
Sorry, for now, I can't 🙃
I recently reinstalled VSCodium and overwrote the product.json file. After that, the student subscription on connected GitHub account expired🤣 Currently i'm in Copilot Chat waitlist. Not sure how to make it work again.

**Comment by hronro** [comment]
I just downloaded the latest VS Codium and the latest Copilot Chat extension, and when I try to install the .vsix file, I got this error:

<img width="1136" alt="CleanShot 2023-07-07 at 12 37 50@2x" src="https://github.com/VSCodium/vscodium/assets/15059605/b3d50295-b5b4-4d3e-a7b9-9f5574a2608c">

**Comment by Neko-Box-Coder** [comment]
Hey, has anyone who has access to chat (and lab) have tried the insider edition of vscodium?
https://github.com/VSCodium/vscodium-insiders

It will also be nice if a link of insider to be added to README since it is not obvious that it exists.

**Comment by Neko-Box-Coder** [comment]
I opened an [issue](https://github.com/orgs/community/discussions/68570) for copilot chat. Feel free to upvote and add any details/comments to it

**Comment by GitMensch** [comment]
> Hey, has anyone who has access to chat (and lab) have tried the insider edition of vscodium? https://github.com/VSCodium/vscodium-insiders
> 
> It will also be nice if a link of insider to be added to README since it is not obvious that it exists.

Done with https://github.com/VSCodium/vscodium/commit/b6676144488271e25cf8f4d9cdb7ebfde136ec90 :-)
... along with the request to add insider version where not available
- [ ] https://github.com/VSCodium/vscodium/issues/1666
- [ ] https://github.com/flathub/com.vscodium.codium/issues/230
- [ ] https://github.com/ScoopInstaller/Versions/issues/1390
- [ ] for choco by mail to the maintainer

**Comment by Neko-Box-Coder** [comment]
@clockcoinG1 I assume you are talking about the chat extension.js.

I am going through it right now (unfortunately) but it is way too many lines and I am no expert in js.
Which part of the extension.js do I need to change?

**Comment by Neko-Box-Coder** [comment]
It seems like it is trying to call the getSession from the vscode module but it returned undefined.

```js
return await vscode.authentication.getSession("github", ['user:email'], {silent: !0}) ?? 
        await vscode.authentication.getSession("github", ['read:user'], {silent: !0});
```

this is under `__webpack_modules__` in `31041` in `t.getSession` if anyone is interested enough to dive in.

**Comment by AlexGrafe** [comment]
Could someone provide a step by step explanation of that? @clockcoinG1 perhaps?
Or could this be put into some "CoPilot Chat Installer" script or even extension?
I'm finding it difficult to see which are now the exact steps after the multiple answers given.

Thanks to all

**Comment by Neko-Box-Coder** [comment]
Yeah, I tried to follow the instructions but failed to even reach the point where @clockcoinG1 got. 
It failed before sending any of the authentication tokens, where it couldn't even start a session.
I gave up after that since it was really a major pain to debug it.

It is possible that I might have missed something but that's as far as I got.

To be fair, the version of chat I was using seems to be different from @clockcoinG1 as well so that could also be a reason.

Ideally the vscode team should fix this, it will be great if you guys can upvote the [issue](https://github.com/orgs/community/discussions/68570) if you haven't.

**Comment by trinitronx** [comment]
I just managed to hack / patch VSCode OSS's `product.json` + the extension's `/extension/package.json` to get it working on Manjaro's packaged:

- `extra/code 1.83.0-1`
- Plus also installed: `aur/code-features 1.83.0-1 (+49 1.12)`

**Note:** (For ArchLinux-based distros) The `extra/code` repo/package is known as "[Code OSS][1]" variant of a VSCodium distribution.  Meanwhile, the `aur/code-features` repo/package also patches the `/usr/lib/code/product.json` to enable some API proposals and other things.

The changes I had to make on top of this were in the following diff (note my `/usr/lib/code/product.json` had tab indentations instead of spaces, so this diff may not apply cleanly for everyone without ignoring whitespace):


```diff
--- a/product.json	2023-10-20 11:43:51.228017157 -0600
+++ b/product.json	2023-10-20 11:43:51.228017157 -0600
@@ -1,16 +1,22 @@
 [
-  "handleIssueUri",
   "interactive",
   "interactiveUserActions",
-  "terminalContextMenu",
+  "chatProvider",
+  "codeActionAI",
+  "findTextInFiles",
+  "textSearchProvider",
   "terminalDataWriteEvent",
+  "terminalExecuteCommandEvent",
   "terminalSelection",
   "terminalQuickFixProvider",
-  "chatSlashCommands",
-  "chatVariables",
-  "chatAgents",
+  "handleIssueUri",
   "readonlyMessage",
-  "chatProvider",
+  "chatVariables",
   "mappedEditsProvider",
-  "aiRelatedInformation"
+  "aiRelatedInformation",
+  "chatAgents",
+  "chatAgents2",
+  "chatAgents2Additions",
+  "defaultChatAgent",
+  "contribSourceControlInputBoxMenu"
 ]
```

Finally, the other necessary change was to unpack the `.vsix` and edit: `extension/package.json` to modify the supported version pin under `"engines": { "vscode": "__VERSION_HERE", ... }`

I changed it from: `^1.84.0-20231017` to mach my version of `/usr/bin/code --version`

```console
$ /usr/bin/code --version                                                                                                                                
1.83.0
e7e037083ff4455cf320e344325dacb480062c3c
x64
```

Relevant part of `extension/package.json`:

```json
"engines": {
  "vscode": ">=1.83.0",
  "npm": ">=9.0.0",
  "node": ">=18.0.0"
}
```

### Steps:

0. Quit VSCode if running
1. Backup `/usr/lib/code/product.json`

       cp /usr/lib/code/product.json /path/to/backup-directory/product.json.$(date +%Y-%m-%d).bak

2. Patch `/usr/lib/code/product.json`

       cd /usr/lib/code && sudo patch -p1 --ignore-whitespace < /path/to/product_json.patch

3. Unpack `.vsix`:

       mkdir /tmp/GitHub.copilot-chat-0.9.2023102002.vsix.unpacked
       unzip -d /tmp/GitHub.copilot-chat-0.9.2023102002.vsix.unpacked/  ~/Downloads/GitHub.copilot-chat-0.9.2023102002.vsix

4. Change `extension/package.json` (it's a minified JSON, so search for `engines`)

       # I used vim... but feel free to use your favorite text editor
       vim /tmp/GitHub.copilot-chat-0.9.2023102002.vsix.unpacked/extension/package.json

5. Save the file & quit editor
6. Repack the patched `.vsix`:

       cd /tmp/GitHub.copilot-chat-0.9.2023102002.vsix.unpacked
       zip -r  /tmp/GitHub.copilot-chat-0.9.2023102002.patched-0.83-0.vsix  .

7. Manually install the **patched** `.vsix`:
    - Open `Code OSS`
    - Go to `Extensions` (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>x</kbd>)
    - Click the <kbd>...</kbd> kebab menu icon (hover tooltip says "`Views and More Actions...`")
    - Click "`Install from VSIX...`"
    - Browse for your patched `.vsix` file: `/tmp/GitHub.copilot-chat-0.9.2023102002.patched-0.83-0.vsix`
    - Optional, but recommended: Copy the patched `.vsix` installer to somewhere for backup purposes

          cp /tmp/GitHub.copilot-chat-0.9.2023102002.patched-0.83-0.vsix ~/path/to/some/vsix/installers-backupdir 

[1]: https://wiki.archlinux.org/title/Visual_Studio_Code

**Comment by AlexGrafe** [comment]
@trinitronx I believe your patch file specifically calls out line `534` while in my version of the file it's somewhere else. The `patch` command won't work then. Anyone else reproducing this would need to adapt that.

**Comment by trinitronx** [comment]
> @trinitronx I believe your patch file specifically calls out line `534` while in my version of the file it's somewhere else. The `patch` command won't work then. Anyone else reproducing this would need to adapt that.

Yes, that's to be expected.  Especially so, given that this patch was generated on Manjaro against the already patched `product.json` (by the [aur/code-features][1] package).  As such, it's safe to assume that it may not apply cleanly to every distro's `product.json` file given the differences in line numbers, etc...

One trick is to try applying it with fuzz level increased (e.g. `fuzz` `>2`):

    cd /usr/lib/code && sudo patch --fuzz=3 -p1 --ignore-whitespace < /path/to/product_json.patch

Another trick is to modify the line numbers in the unified patch format to match your variant of the file (change `NNN` to match your file's starting line number that matches the patch context):

    --- a/product.json	2023-10-20 11:17:19.854726954 -0600
    +++ b/product.json	2023-10-20 11:20:43.678596193 -0600
    @@ -NNN,20 +NNN,26 @@

Of course, any `patch`-based method is prone to hunks being rejected and failing to patch cleanly.  Manual editing is the best bet in this case.  I guess this is also why the [aur/code-features package scripts do the JSON merge in Python](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=code-features#n23) instead.


[1]: https://aur.archlinux.org/packages/code-features

**Comment by 42Willow** [comment]
Copilot worked out of the box for me, but I can't load gh copilot chat as it is "not compatible" when trying to load from VSIX. Does anyone know of a fix?

**Comment by 0xEEEE** [comment]
> > Yes, it's possible to make Copilot Chat work by tweaking some lines in the product.json file.
> 
> @wtf403 Would you mind sharing what tweaks are needed to get this working? I'm using VSCodium Insider, and have the Copilot Chat extension installed. Regular Copilot features work but Chat doesn't. The extension logs for Copilot Chat say
> 
> ```
> [INFO] [auth] [2023-07-05T16:11:08.579Z] GitHub login failed
> [ERROR] [default] [2023-07-05T16:11:08.583Z] You are not signed in to GitHub. Please sign in to use Copilot.
> ```
> 
> even though I am definitely logged in (since regular Copilot works).
> 
> Edit: forgot to mention but I'm also in the Chat private beta.

Try this, it's worked for me.

`
        "GitHub.copilot-chat": [
            "handleIssueUri",
            "interactive",
            "interactiveUserActions",
            "terminalDataWriteEvent",
            "terminalExecuteCommandEvent",
            "terminalSelection",
            "terminalQuickFixProvider",
            "chatProvider",
            "chatVariables",
            "chatAgents2",
            "chatAgents2Additions",
            "defaultChatAgent",
            "readonlyMessage",
            "mappedEditsProvider",
            "aiRelatedInformation",
            "codeActionAI",
            "findTextInFiles",
            "textSearchProvider",
            "scmInputBoxValueProvider",
            "contribSourceControlInputBoxMenu"
        ],
    ......
    "trustedExtensionAuthAccess": [
        "vscode.git",
        "vscode.github",
        "github.remotehub",
        "github.vscode-pull-request-github",
        "github.codespaces",
        "github.copilot",
        "github.copilot-chat"
    ],
    "trustedExtensionProtocolHandlers": [
        "vscode.git",
        "vscode.github-authentication"
    ],
`

**Comment by RedBed24** [comment]
I still can't get it to work...

Codium version: 1.85.1
Extensions version:
GitHub.copilot@1.143.0
GitHub.copilot-chat@0.12.2023120701
OS: Nobara Linux 38 (KDE Plasma)

Settings in `product.json`:
```JSON
	"extensionEnabledApiProposals": {
		"GitHub.copilot": [
			"inlineCompletionsAdditions",
			"interactive",
			"interactiveUserActions",
			"terminalDataWriteEvent"
		],
		"GitHub.copilot-nightly": [
			"inlineCompletionsAdditions",
			"interactive",
			"interactiveUserActions",
			"terminalDataWriteEvent"
		],
		"GitHub.copilot-chat": [
			"handleIssueUri",
			"interactive",
			"interactiveUserActions",
			"terminalDataWriteEvent",
			"terminalExecuteCommandEvent",
			"terminalSelection",
			"terminalQuickFixProvider",
			"chatProvider",
			"chatVariables",
			"chatAgents2",
			"chatAgents2Additions",
			"defaultChatAgent",
			"readonlyMessage",
			"mappedEditsProvider",
			"aiRelatedInformation",
			"codeActionAI",
			"findTextInFiles",
			"textSearchProvider",
			"scmInputBoxValueProvider",
			"contribSourceControlInputBoxMenu"
		]
	},
	"trustedExtensionAuthAccess": [
		"vscode.git",
		"vscode.github",
		"github.remotehub",
		"github.vscode-pull-request-github",
		"github.codespaces",
		"github.copilot",
		"github.copilot-chat"
	],
	"trustedExtensionProtocolHandlers": [
		"vscode.git",
		"vscode.github-authentication"
	]
```

I'm still getting:
```
2023-12-24 17:08:13.888 [info] [auth] GitHub login failed
2023-12-24 17:08:13.892 [info] [extension] You are not signed in to GitHub. Please sign in to use Copilot.
```

**Comment by AlfredoDinunzioTR** [comment]
> I still can't get it to work...

Not sure if you are on Arch Linux but I switched from VSCodium to Code (OSS). Then I tried the fixes here from @trinitronx  and @LewsTherinTelescope  and mine is now working!

**Comment by bruxr** [comment]
Receiving the same `GitHub login failed` as well. Copilot Chat installed via VSIX was working fine last December

**Comment by T-vK** [comment]
I literally just installed [vscodium-bin-marketplace](https://aur.archlinux.org/packages/vscodium-bin-marketplace) and was able to install GitHub Copilot Chat from the VSCodium UI without any issues. No need to manually download .vsix files or manipulate a product.json file after every update.

Depending on how you installed VSCodium, you might prefer one of these options: 
- [vscodium-marketplace](https://aur.archlinux.org/packages/vscodium-marketplace)
- [vscodium-marketplace-git](https://aur.archlinux.org/packages/vscodium-marketplace)
- [vscodium-insiders-marketplace](https://aur.archlinux.org/packages/vscodium-marketplace)
- [vscodium-insiders-bin-marketplace](https://aur.archlinux.org/packages/vscodium-marketplace)

For me (having [vscodium-bin](https://aur.archlinux.org/packages/vscodium-bin)), my preferred choice was [vscodium-marketplace-bin](https://aur.archlinux.org/packages/vscodium-bin-marketplace).

I'm using an the latest Manjaro Linux.

**Comment by TimTheBig** [comment]
I installed **GitHub Copilot Chat** from the **VSCodium UI** with the **visualstudio marketplace** and after fixing a lot of errors with the `product.json`, **I can not fix**: `vscodium github-copilot-chat Chat failed to load. Please ensure that the GitHub Copilot Chat extension is up to date.` which appears even if I'm using the **pre-release version** of the extension.

**Comment by maasikai** [comment]
> I installed **GitHub Copilot Chat** from the **VSCodium UI** with the **visualstudio marketplace** and after fixing a lot of errors with the `product.json`, **I can not fix**: `vscodium github-copilot-chat Chat failed to load. Please ensure that the GitHub Copilot Chat extension is up to date.` which appears even if I'm using the **pre-release version** of the extension. Even though the main copilot extension works.

I managed to get the login to work by adding "autthLearnMore" into "GitHub.copilot-chat" permissions in product.json, restarting vscodium, pressing ctrl+p and ">GitHub Copilot: Sign in to Chat" and going through the auth flow. However, there are still some uncaught errors that prevent the chat from working.

**Comment by TimTheBig** [comment]
I keep getting:
Uncaught Errors (1)
```
 n.onDidPerformAction is not a function
TypeError: n.onDidPerformAction is not a function at OY.createAgent (/Users/me/.vscode-oss/extensions/github.copilot-chat-0.14.1/dist/extension.js:861:10236) at OY.registerDefaultAgent
```

**Comment by maasikai** [comment]
> I keep getting: Uncaught Errors (1)
> 
> ```
>  n.onDidPerformAction is not a function
> TypeError: n.onDidPerformAction is not a function at OY.createAgent (/Users/me/.vscode-oss/extensions/github.copilot-chat-0.14.1/dist/extension.js:861:10236) at OY.registerDefaultAgent
> ```

Finally got it running. Switching to vscodium-insiders seemed to do the trick.

**Comment by TimTheBig** [comment]
**vscodium stable** `1.88.1.24104` works for me with `product.json` mods.

**Comment by melroy89** [comment]
> **vscodium stable** `1.88.1.24104` works for me with `product.json` modifications.

GitHub Copilot chat released just a moment ago, which might give you a message like: `Unable to install extension 'github.copilot-chat' as it is not compatible with VSCodium '1.x.x.`.

**Comment by melroy89** [comment]
> GitHub Copilot chat released a new version of the extension just a moment ago, which might give you a message like: `Unable to install extension 'github.copilot-chat' as it is not compatible with VSCodium '1.x.x.`. So you might need to download an older version or manually changing the extension if you really want to (no guarantees): [#1753 (comment)](https://github.com/VSCodium/vscodium/issues/1753#issuecomment-2064992100)

In fact, all latest versions of GitHub Copilot Chat are TOO NEW and they only show the latest 5 versions on the marketplace web site.... omg.

So I needed to use: https://stackoverflow.com/questions/76211091/how-can-i-get-a-list-of-a-vs-code-extensions-versions

**Comment by TimTheBig** [comment]
>>
> Then I saw errors that it also needed the `GitHub.vscode-pull-request-github ` extenstion? So I [also downloaded & installed that](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github). I hope it's not required, but OK.

`GitHub.vscode-pull-request-github` is not required.

**Comment by melroy89** [comment]
Copilot Chat is just not working with VScodium (just copilot does work, but not Chat):

![copilot_chat_not_working](https://github.com/VSCodium/vscodium/assets/628926/e70a7f7d-e31a-45be-8597-65922dea7833)

**Comment by TimTheBig** [comment]
It works for me, all you have to do is use the marketplace from VSCode and add the additional lines to your `product.json`.

**Comment by GitMensch** [comment]
Other than the vscode marketplace, did you use something else? Which version of VSCodium and which extension(s) do you use?

You mean these additions? https://github.com/VSCodium/vscodium/issues/1546#issuecomment-1793619431

I see no reason to not include them by default, @daiyam do you?

**Comment by zeroaddresss** [comment]
> I keep getting: Uncaught Errors (1)
> 
> ```
>  n.onDidPerformAction is not a function
> TypeError: n.onDidPerformAction is not a function at OY.createAgent (/Users/me/.vscode-oss/extensions/github.copilot-chat-0.14.1/dist/extension.js:861:10236) at OY.registerDefaultAgent
> ```

@TimTheBig I am getting the same error now, how did you fix this? I'm using Copilot Chat extension `v0.14.2024032901` and VSCodium `v1.88.1.24104`. Already made all the required changes in the `product.json`.
Don't really want to move to the Insiders build though, I would like to stick to my standard VSCodium if possible.

**Comment by TimTheBig** [comment]
Did you use the VS code marketplace.

**Comment by daiyam** [comment]
@GitMensch, my answer from #1852

> VSCodium is using the same `extensionEnabledApiProposals` as Visual Studio Code. I've checked.
> 
> Here the script doing it https://github.com/VSCodium/vscodium/blob/master/build/update_api.sh
> 
> Those Apis depend on the version of the editor and of the extension. Your needs seem like an older version

**Comment by zeroaddresss** [comment]
> As far as I know you have to use the VS code marketplace. The extension may have been updated, you might have to wait for a VSCodium update.

@TimTheBig you mean [this marketplace](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat) or the built-in extensions marketplace in VSCodium UI?

**Comment by TimTheBig** [comment]
You have to modify your `product.json`  to use the VSCode [marketplace](https://marketplace.visualstudio.com). 
This guide worked for me: [VSCode Gallery In VSCodium](https://github.com/OliverKeefe/vscode-extensions-in-vscodium?tab=readme-ov-file#extensions--marketplace).

**Comment by daiyam** [comment]
@TimTheBig Which version are you using? (VSCodium and Copilot)

**Comment by TimTheBig** [comment]
VSCodium:
```
Version: 1.88.1
Release: 24104
Commit: 0d01a72525276e5e3771fe5851b9c83de0de1e2b
Date: 2024-04-13T01:43:30.924Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```
GitHub Copilot: `v1.181.0`
GitHub Copilot Chat: `v0.14.1`

**Comment by TimTheBig** [comment]
> yelp! is there a script to patch the whole thing without manual tweaks? argument1: path to product.json, argumetn2: path to /support product.json etc.
> 
> spent several hours to make this work but failing miserably. installed from vscode marketplace ([#1546 (comment)](https://github.com/VSCodium/vscodium/issues/1546#issuecomment-2068291176)):
>
What version of **copilot-chat** is the store page showing?

**Comment by afarah1** [comment]
For me only chat does not work (same symptom as https://github.com/VSCodium/vscodium/issues/1546#issuecomment-2066178867, pressing enter does nothing), no error logs.

I'm using VSCodium

```
Version: 1.90.2
Release: 24171
Commit: 7d98c6de73fb939f1eb4b8a500c569b858b2d297
Date: 2024-06-19T18:42:40.159Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.6.30-gentoo
```

Having installed CoPilot `v1.171.0` from the UI, 

I've tried making the changes to product.json mentioned in https://github.com/VSCodium/vscodium/issues/1546#issuecomment-1793619431, which generated some error logs because the proposals no longer exist, and did not solve the issue.

**Comment by afarah1** [comment]
For me completions worked but **chat did nothing when I pressed enter**, the same issue as @melroy89 (https://github.com/VSCodium/vscodium/issues/1546#issuecomment-2066178867). Turns out it's a matter of matching the correct vscodium and copilot chat versions. I'll present one solution, but it may be possible to match different versions and have it work.

1. Install vscodium 1.90.2 from your favorite source. This is the current version in Gentoo.
2. Download the latest GitHub CoPilot (click Download Extension): https://marketplace.visualstudio.com/items?itemName=GitHub.copilot
3. Download GitHub CoPilot Chat 0.17.20* (notice you need two extensions!): https://marketplace.visualstudio.com/_apis/public/gallery/publishers/GitHub/vsextensions/copilot-chat/0.17.2024062801/vspackage
4. Change `package.json` from the chat VSIX to match your vscodium version: In a clear folder run `unzip  GitHub.copilot-chat-0.17.2024062801.vsix`, `rm GitHub.copilot-chat-0.17.2024062801.vsix`, open `extension/package.json` in your favorite text editor and change `"engines":{"vscode":"^1.92.0",` to `"engines":{"vscode":"^1.90.0",`. Save the file then run `zip -r GitHub.copilot-chat-0.17.2024062801.vsix .`
5. Open vscodium, go to Extensions, click ... then Install from VSIX and install both files - copilot and the chat one you modified

You're done, enjoy!

![out3](https://github.com/VSCodium/vscodium/assets/3854807/5d8b8dbd-5c35-47e8-811b-2a3c5bb16df6)

**Comment by melroy89** [comment]
> Is there a compatible Github Copilot Chat version in VSCodium version 1.93.0?

Yesn't

**Comment by GitMensch** [comment]
Just out of curiosity: What is the benefit of using a using non-proprietary, non-telemetry-defaulting binary of vscode when installing a proprietary binary extension  (which is likely licensed to be only used with Visual Studio Code) that talks the whole time to a service that's not under your control using non-free binaries of a non-free language model (trained on free software) which likely has several kinds of telemetry?
I seem to miss several important points here and would like to get the "real picture".

**Comment by ahmet-cetinkaya** [comment]
You're right. But the idea is to reduce telemetry as much as possible. Sometimes not everything is perfect. I personally use Github Copilot because I can't find a free open source model that works well.

**Comment by gylfirst** [comment]
After replacing again the product.json tu use microsoft store, i was able to reinstall both extensions for copilot (standard + chat).
Hope that will works for you

**Comment by GitMensch** [comment]
If you are not aware - you don't need to replace the product.json but can override it per environment variable / user config file (upstream vscode sadly did not implement the PR because "they are working on providing a user endpoint" ... since some years now - so that's VSCodium only): https://github.com/VSCodium/vscodium/blob/master/docs/index.md#how-to-use-a-different-extension-gallery

**Comment by hronro** [comment]
comment.

**Comment by peter-fb** [comment]
> Just out of curiosity: What is the benefit of using a using non-proprietary, non-telemetry-defaulting binary of vscode when installing a proprietary binary extension (which is likely licensed to be only used with Visual Studio Code) that talks the whole time to a service that's not under your control using non-free binaries of a non-free language model (trained on free software) which likely has several kinds of telemetry?

It's true, using the Copilot extension in VSCodium does indeed violate the terms of service for Microsoft's Visual Studio Marketplace. So, if you want to use Copilot, you're simply better off using VS Code.

**Comment by VGerris** [comment]
check :
https://github.com/VSCodium/vscodium/discussions/1487#discussioncomment-13927656

I believe the : 	"GitHub.copilot-chat": [ can probably be left alone, it has more permissions by default now.

**Comment by PabloVitasso** [comment]
https://github.com/VSCodium/vscodium/discussions/1487#discussioncomment-13927656 - this works for me
