### ISSUE TITLE
IntelliCode won't work on VSCodium

### ISSUE THREAD

**Issue by cdhainaut** [VSCodium/vscodium#1646]
Hi,

I am not able to use IntelliCode inside VSCodium. I checked with VSCode and it works perfectly.
I have same release version on VSCodium and VSCode (1.82.2)
The extensions I have are:
- Pylance v2023.9.10
- IntelliCode 1.2.30
- Python v2023.16.0
On both VSCodium and VSCode

I run a laptop with Linux Mint 21.2 on it

The error I get on VSCodium is:
```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
vs-intellicode-python was passed a model: {}.
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at w._tryExecuteCommand (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:1536:16054)
    at w.executeCommand (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:1536:15936)
Error while activating Python: {}
```

Thank you

**Comment by GitMensch** [comment]
Did you have a look at https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility?

**Comment by cdhainaut** [comment]
Hi,

Thanks for the link. Although I don't quite understand why suddenly it does not work anymore as I did not have any issue in the past year using codium

**Comment by daiyam** [comment]
It depends on the goodwill of those extensions. Sometime times it works, some others it doesn't.

**Comment by bebenlebricolo** [comment]
+1  here.
Tested altogether with VSCode Insiders as well -> No pb in VScode Insiders, works out of the box.

That's weird, as regular logs in vscodium don't provide much intel (I mean Python Extension logs in the Output window) about anything being wrong !

However, I just found that in the settings > Python > Language Server, if you change that from default (Pylance) to the usual fallback LServer (Jedi), then at least autocompletion seems to start working again.
Might not be as powerful as their new Pylance LS (if Jedi is the fallback, I suppose there are good reasons for this), but at least it gets it functional again...

![image](https://github.com/VSCodium/vscodium/assets/29211687/93a81c69-3c8f-4849-96b5-9e4b5985bd66)

Probably some more troubleshooting is required on the Pylance side (?).

**Comment by TechPro424** [comment]
Same issue, even Jedi does not give autocomplete in my case

**Comment by raycekar** [comment]
Sadly same here, 

Version: 1.85.1 (user setup)
Release: 23348
Commit: 08e6c15293922dd53a864bb041be381322fee401
Date: 2023-12-14T20:44:42.949Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Latest python extension.

Installed vscode with python addon and does in fact work

**Comment by TechPro424** [comment]
Bump

**Comment by GitMensch** [comment]
> Language server is set to "Default". Pylance is used as current language server.
> ...
> Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found

Pylance is proprietary, according to the setting definition it should only be chosen if available, which isn't the case.
Looks like an error in that extension (you may want to file an issue "Default setting for Language Server chooses Pylance while not available" there) - which you may be able to workaround by explicit setting `python.languageServer` to `Jedi`.

> Did you have a look at https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility?

> It depends on the goodwill of those extensions. Sometime times it works, some others it doesn't.

I'm not sure if there's anything more we can do, so consider to close this issue.
As all things mentioned here are issues with Microsoft extensions, not with vscodium I suggest to create issues there "does not work with vscode open source builds" in those extensions, this may help you more. Note that - as mentioned in the wiki - some LSP explicit are only licensed for Microsoft binaries, so there's no use in complaining (neither here, nor at Microsoft) at all.

**Comment by TechPro424** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright
using this extension and Jedi lang server, the experience has improved a lot
Pylance needs to be uninstalled for this to work

**Comment by fithisux** [comment]
If you use all the ms-python extensions on VSCodium 1.9.0 @cdhainaut  (of course select black or autopep8 for formatters) and jedi server on 3.12.3 python on windows, with jedi language server, not only everything works fine but it also enforces good programming practices. I'm on Windows x64 10 Pro. I was very pleasantly surprised that all worked that good. I also have VSCode for my main work on Python but the experience was day and night vs one year before. I have not yet used python test runner on VSCodium.

**Comment by GustavoWidman** [comment]
Rolling back Pylance to 2023.6.40 seems to work fine (if you would rather run a year old version of the extension).

**Comment by fithisux** [comment]
Since August I work exlusively with VScodium and jedi server for all my professional work. No issues.

MS extensions, jlatest Jedi server, Python 3.13 on windows 10 x64 and ruff plugin.

**Comment by GitMensch** [comment]
> Since August I work exlusively with VScodium and jedi server for all my professional work. No issues.
> 
> MS extensions, latest Jedi server, Python 3.13 on windows 10 x64 and ruff plugin.

Can you please outline what you had to do? for this setup (apart from the python binaries). Also, what is that plugin for/where it is used (and how installed)?

**Comment by fithisux** [comment]
OK @GitMensch .

First of all I am on Windows 10 x64.

I installed Python 3.13.1 in c:\]winoss\python3 and allowed it to be on the path (during installation)
I installed VScodium c:\winoss\vscodium and allowed it to be on the path (during installation)

In Python I installed

```
pip3 install -upgrade mypy mypy-extensions ruff jedi-language-server
```

I removed any remnants of previous vscodium extensions (I erased in my user folder the vscodium folder
e.g. c:\Users\VasilisAnagnostopoul\.vscode-oss\)

I open VScodium

and install

ms-python => Python, Python Debugger , Mypy type checker
charliermarsh => Ruff


And now after close and restart (maybe not required)

File > Preferences > Settings extensions > Python

Language Server > Jedi

File > Preferences > Settings extensions > Ruff

Enable > tick it.

Close VScodium and open it.

Now load your project folder.

Did it work for you?

**Comment by GitMensch** [comment]
That works fine on "modern" systems (if you don't need the debugger or mypy you can drop ms-python and its sister debug extension as well as pip3 and any packages from it). For everything that is part of the RedHat8 family (which only distributes python 3.6.8), this setup currently doesn't work. (ref: https://github.com/astral-sh/ruff-vscode/issues/660)

**Comment by rkfg** [comment]
Try [downgrading Pylance to 2023.6.40](https://github.com/MicrosoftDocs/intellicode/issues/509#issuecomment-1982372616), I also use Codium and affected by this bug, downgrading allows Pylance work again. Disable autoupdates for this extension if it helps.

**Comment by dazu89** [comment]
How are you doing with Pylance on your current setup? I am trying to use VSCodium 1.102.04606 together with Pylance 
2025.6.102 and Python 3.13.5.  My product.json under ~/.config/VSCodium reads
```
{
  "extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items"
  }
}
```
unfortunately, I cannot get inline suggestions to work, as tool-tip at the lower right bottom rightly observes: "No inline suggestion available".
Please let me know, if you have a work around.
