### ISSUE TITLE
dev contaier: `Failed to download VS Code Server`

### ISSUE THREAD

**Issue by ndlarsen** [VSCodium/vscodium#1696]
**Describe the bug**
Dev containers extension fails to download `VS Code Server` while using vscodium but not vscode.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. install dev containers extention
2. open project containing supplied dev container definitions (below)
3. rebuild/open dev container

**Expected behavior**
dev container being able to download relevant resources for container setup

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS:
 ```
  $ uname -a
  Linux master 5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
  ```
 - Architecture x86_64
 - Version:
 ```
 Version: 1.83.1
 Release: 23285
 Commit: 36d13de33ac0d6c684f10f99cff352e2f58228b3
 Date: 2023-10-12T18:26:29.496Z
 Electron: 25.8.4
 ElectronBuildId: undefined
 Chromium: 114.0.5735.289
 Node.js: 18.15.0
 V8: 11.4.183.29-electron.0
 OS: Linux x64 5.15.0-86-generic
 ```
 dev containers: `v0.315.1`
 - App Manager: apt using paulcarroty's apt respository
 - Sandboxed: no

**Additional context**

**dev container definition**
All default generated by extension

Dockerfile
```
FROM mcr.microsoft.com/devcontainers/javascript-node:1-18-bookworm

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=10
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

# [Optional] Uncomment if you want to install more global node modules
# RUN su node -c "npm install -g <your-package-list-here>"
```

devcocntainer.json
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/javascript-node-postgres
{
	"name": "Node.js & PostgreSQL",
	"dockerComposeFile": "docker-compose.yml",
	"service": "app",
	"workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}"

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// This can be used to network with other containers or with the host.
	// "forwardPorts": [3000, 5432],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "yarn install",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

docker-compose.yml
```
version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
```

**Logs**

Notable part of log:
```
Failed to download VS Code Server (https://update.code.visualstudio.com/commit:36d13de33ac0d6c684f10f99cff352e2f58228b3/server-linux-x64/stable): HTTP 404 - Not Found
[4760 ms] Retrying to download VS Code Server.
[4874 ms] Error: Server returned 404
    at h (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:676:36488)
    at T.download (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:677:1873)
[10375 ms] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f686f6d652f6e646c617273656e2f7372632f74656d702f7765625f6170695f646576222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f686f6d652f6e646c617273656e2f7372632f74656d702f7765625f6170695f6465762f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f686f6d652f6e646c617273656e2f7372632f74656d702f7765625f6170695f6465762f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f686f6d652f6e646c617273656e2f7372632f74656d702f7765625f6170695f6465762f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/workspaces/web_api_dev'
```

Full log
```
[18 ms] Dev Containers 0.315.1 in VS Code 1.83.1 (36d13de33ac0d6c684f10f99cff352e2f58228b3).
[17 ms] Start: Resolving Remote
[44 ms] Setting up container for folder or workspace: /home/ndlarsen/src/temp/web_api_dev
[47 ms] Start: Check Docker is running
[47 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[78 ms] Server API version: 1.43
[79 ms] Start: Run: docker volume ls -q
[100 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/ndlarsen/src/temp/web_api_dev --filter label=vsch.quality=stable
[122 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ndlarsen/src/temp/web_api_dev --filter label=devcontainer.config_file=/home/ndlarsen/src/temp/web_api_dev/.devcontainer/devcontainer.json
[145 ms] Start: Run: docker inspect --type container ba0fe01f4629 f38c0d9f35ce
[167 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ndlarsen/src/temp/web_api_dev
[190 ms] Start: Run: docker inspect --type container ba0fe01f4629 f38c0d9f35ce
[212 ms] Start: Run: /usr/share/codium/codium /home/ndlarsen/.vscode-oss/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/ndlarsen/src/temp/web_api_dev --id-label devcontainer.local_folder=/home/ndlarsen/src/temp/web_api_dev --id-label devcontainer.config_file=/home/ndlarsen/src/temp/web_api_dev/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ndlarsen/src/temp/web_api_dev/.devcontainer/devcontainer.json --mount-workspace-git-root
[453 ms] @devcontainers/cli 0.51.3. Node.js v18.15.0. linux 5.15.0-86-generic x64.
[453 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ndlarsen/src/temp/web_api_dev --filter label=devcontainer.config_file=/home/ndlarsen/src/temp/web_api_dev/.devcontainer/devcontainer.json
[479 ms] Start: Run: docker inspect --type container ba0fe01f4629 f38c0d9f35ce
[754 ms] Start: Run: /usr/share/codium/codium /home/ndlarsen/.vscode-oss/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/ndlarsen/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-someValue.sessionId_1697644021665 --workspace-folder /home/ndlarsen/src/temp/web_api_dev --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ndlarsen/src/temp/web_api_dev --id-label devcontainer.config_file=/home/ndlarsen/src/temp/web_api_dev/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ndlarsen/src/temp/web_api_dev/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[964 ms] @devcontainers/cli 0.51.3. Node.js v18.15.0. linux 5.15.0-86-generic x64.
[964 ms] Start: Run: docker buildx version
[987 ms] 
[987 ms] docker: 'buildx' is not a docker command.
See 'docker --help'

[988 ms] Exit code 1
[988 ms] Start: Resolving Remote
[994 ms] Start: Run: docker-compose version --short
[1410 ms] Docker Compose version: 1.25.0
[1411 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=web_api_dev_devcontainer --filter label=com.docker.compose.service=app
[1432 ms] Start: Run: docker inspect --type container ba0fe01f4629
[1453 ms] Start: Run: docker-compose -f /home/ndlarsen/src/temp/web_api_dev/.devcontainer/docker-compose.yml config
[1865 ms] services:
  app:
    build:
      context: /home/ndlarsen/src/temp/web_api_dev/.devcontainer
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:db
    volumes:
    - /home/ndlarsen/src/temp:/workspaces:cached
  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw
version: '3.3'
volumes:
  postgres-data: {}

[1870 ms] Start: Run: docker -v
[1888 ms] Start: Run: docker events --format {{json .}} --filter event=start
[1892 ms] PersistedPath=/home/ndlarsen/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-containers/data, ContainerHasLabels=true
[1892 ms] Container was created with these config files: /home/ndlarsen/src/temp/web_api_dev/.devcontainer/docker-compose.yml,/home/ndlarsen/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1697642390859.yml,/home/ndlarsen/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1697642391391.yml
[1892 ms] Restoring /home/ndlarsen/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1697642390859.yml from persisted storage
[1893 ms] Restoring /home/ndlarsen/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1697642391391.yml from persisted storage
[1893 ms] Start: Run: docker-compose --project-name web_api_dev_devcontainer -f /home/ndlarsen/src/temp/web_api_dev/.devcontainer/docker-compose.yml -f /home/ndlarsen/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1697642390859.yml -f /home/ndlarsen/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1697642391391.yml up -d --no-recreate
Starting web_api_dev_devcontainer_db_1 ... done
Starting web_api_dev_devcontainer_app_1 ... done
[2888 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=web_api_dev_devcontainer --filter label=com.docker.compose.service=app
[2906 ms] Start: Run: docker inspect --type container ba0fe01f4629
[2929 ms] Start: Inspecting container
[2929 ms] Start: Run: docker inspect --type container ba0fe01f46291d612ecfc38482a763a546b48422fd4a4833597ff77768949dfd
[2948 ms] Start: Run in container: /bin/sh
[2953 ms] Start: Run in container: uname -m
[3067 ms] x86_64
[3067 ms] 
[3067 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[3068 ms] PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[3068 ms] 
[3069 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'node' || grep -E '^node|^[^:]*:[^:]*:node:' /etc/passwd || true)
[3071 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[3072 ms] 
[3072 ms] 
[3072 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[3072 ms] 
[3072 ms] 
[3078 ms] Start: Run: docker inspect --type container ba0fe01f46291d612ecfc38482a763a546b48422fd4a4833597ff77768949dfd
[3099 ms] Start: Run: docker exec -i -u root ba0fe01f46291d612ecfc38482a763a546b48422fd4a4833597ff77768949dfd /bin/sh -c echo "New container started. Keep-alive process started." ; export VSCODE_REMOTE_CONTAINERS_SESSION=someValue.sessionId_1697644021665 ; /bin/sh
[3105 ms] Start: Run: docker-compose version --short
[3209 ms] New container started. Keep-alive process started.
[3530 ms] Start: Run: /usr/share/codium/codium /home/ndlarsen/.vscode-oss/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/ndlarsen/src/temp/web_api_dev --id-label devcontainer.local_folder=/home/ndlarsen/src/temp/web_api_dev --id-label devcontainer.config_file=/home/ndlarsen/src/temp/web_api_dev/.devcontainer/devcontainer.json --container-id ba0fe01f46291d612ecfc38482a763a546b48422fd4a4833597ff77768949dfd --log-level debug --log-format json --config /home/ndlarsen/src/temp/web_api_dev/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root
[3741 ms] @devcontainers/cli 0.51.3. Node.js v18.15.0. linux 5.15.0-86-generic x64.
[3741 ms] Start: Run: docker inspect --type container ba0fe01f46291d612ecfc38482a763a546b48422fd4a4833597ff77768949dfd
[3771 ms] Start: Inspecting container
[3771 ms] Start: Run: docker inspect --type container ba0fe01f46291d612ecfc38482a763a546b48422fd4a4833597ff77768949dfd
[3800 ms] Start: Run in container: /bin/sh
[3806 ms] Start: Run in container: uname -m
[3907 ms] x86_64
[3907 ms] 
[3908 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[3909 ms] PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[3909 ms] 
[3909 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'node' || grep -E '^node|^[^:]*:[^:]*:node:' /etc/passwd || true)
[3911 ms] Start: Setup shutdown monitor
[3912 ms] Forking shutdown monitor: /home/ndlarsen/.vscode-oss/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/shutdown/shutdownMonitorProcess /run/user/1000/vscode-remote-containers-d3637097-3cf7-4ad3-b84b-ca406b984b15.sock dockerCompose Debug /home/ndlarsen/.config/VSCodium/logs/20231018T174659/window1/exthost/ms-vscode-remote.remote-containers 1697644021620
[3920 ms] Start: Run in container: test -d /home/node/.vscodium-server
[3921 ms] 
[3921 ms] 
[3921 ms] Start: Run in container: test ! -f '/home/node/.vscodium-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/node/.vscodium-server/data/Machine' && { > '/home/node/.vscodium-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[3923 ms] 
[3923 ms] 
[3923 ms] Exit code 1
[3924 ms] Start: Run in container: cat /home/node/.vscodium-server/data/Machine/settings.json
[3925 ms] 
[3925 ms] cat: /home/node/.vscodium-server/data/Machine/settings.json: No such file or directory
[3925 ms] Exit code 1
[3925 ms] Start: Run in container: test -d /home/node/.vscodium-server/bin/36d13de33ac0d6c684f10f99cff352e2f58228b3
[3926 ms] 
[3926 ms] 
[3926 ms] Exit code 1
[3926 ms] Start: Run in container: test -d /vscode/vscodium-server/bin/linux-x64/36d13de33ac0d6c684f10f99cff352e2f58228b3
[3927 ms] 
[3927 ms] 
[3927 ms] Exit code 1
[3928 ms] Installing VS Code Server for commit 36d13de33ac0d6c684f10f99cff352e2f58228b3
[3928 ms] Start: Run in container: /bin/sh
[3935 ms] Start: Downloading VS Code Server
[3935 ms] 36d13de33ac0d6c684f10f99cff352e2f58228b3 linux-x64 stable 
[4760 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:36d13de33ac0d6c684f10f99cff352e2f58228b3/server-linux-x64/stable): HTTP 404 - Not Found
[4760 ms] Retrying to download VS Code Server.
[4874 ms] Error: Server returned 404
    at h (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:676:36488)
    at T.download (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:677:1873)
[10375 ms] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f686f6d652f6e646c617273656e2f7372632f74656d702f7765625f6170695f646576222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f686f6d652f6e646c617273656e2f7372632f74656d702f7765625f6170695f6465762f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f686f6d652f6e646c617273656e2f7372632f74656d702f7765625f6170695f6465762f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f686f6d652f6e646c617273656e2f7372632f74656d702f7765625f6170695f6465762f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/workspaces/web_api_dev'
    at r.withProvider (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:645:15395)
    at async r.exists (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:645:18034)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:1867:3343
```

**Comment by daiyam** [comment]
Ya, it seems like we don't support the devcontainer.
It shouldn't try to download the VS Code Server but the REH archive of VSCodium in our releases on GitHub.

**Comment by ndlarsen** [comment]
> Ya, it seems like we don't support the devcontainer. It shouldn't try to download the VS Code Server but the REH archive of VSCodium in our releases on GitHub.

There is a quite a bit of contextual knowledge required to understand the meaning of this. What is the _REH archive_?
Is it possible for VSCodium to support plugins such as Dev Containers or should I move to VSCode (as it seems that I need to for the time being)?

**Comment by xavier83** [comment]
Hit a similar issue when trying devpod, was able to solve by using https://open-vsx.org/extension/jeanp413/open-remote-ssh instead of M$ version.

**Comment by daiyam** [comment]
> VS Code Remote Development extension "stable" releases are tied directly to VS Code releases.

From https://github.com/Microsoft/vscode-remote-release

That extension is closed sourced with a license and code tied to VSCode.

more about extensions compatibility at https://github.com/VSCodium/vscodium/blob/master/docs/extensions-compatibility.md

**Comment by ndlarsen** [comment]
> > VS Code Remote Development extension "stable" releases are tied directly to VS Code releases.
> 
> From https://github.com/Microsoft/vscode-remote-release
> 
> That extension is closed sourced with a license and code tied to VSCode.
> 
> more about extensions compatibility at https://github.com/VSCodium/vscodium/blob/master/docs/extensions-compatibility.md

So the extension is not compatible with VSCodium for various reasons, thank you for giving a somewhat straight answer. As a side note, having had a look at older issues, I also found issue https://github.com/VSCodium/vscodium/issues/1229 which pretty much states the same.

> Hit a similar issue when trying devpod, was able to solve by using https://open-vsx.org/extension/jeanp413/open-remote-ssh instead of M$ version.

This extension does not seem to support the [devcontainer spec](https://containers.dev/implementors/spec/) which is what I need (for work related reasons), thanks though.

Guess using VSCodium for me until an extension fully supporting the devcontainer spec and a license acceptable by the VSCodium team is available.

I am closing the issue as there is no immediate solution.
