### ISSUE TITLE
Oe.show is not a function

### ISSUE THREAD

**Issue by Babs-lua** [VSCodium/vscodium#1747]
Type: <b>Bug</b>

Install Vscodium with sudo apt install vscodium.
Do the "Learn Fundamentals" tutorial. The error will show by clicking on "Browse Recommended Extension". On the bottom right, there will be a issu pop-up with "Oe.show is not a function". By the way, there is nothing in the Extensions Panel to.

VSCodium version: VSCodium 1.84.2 (1fc52b725b3f76b97eadfd988cea42a739ae923f, 2023-11-15T21:57:44.436Z)
OS version: Linux x64 6.5.0-3parrot1-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2625)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.56GB (5.42GB free)|
|Process Argv|--ms-enable-electron-run-as-node|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|14.5.1
prettier-vscode|esb|10.1.0
vscode-github|Kni|0.30.7
python|ms-|2023.20.0
autodocstring|njp|0.6.1
java|red|1.25.0
shellman|Rem|5.6.0
markdown-preview-enhanced|shd|0.8.10
shellcheck|tim|0.35.0

</details>

**Comment by Babs-lua** [comment]
Here is the error from the Developper tool:
```
workbench.desktop.main.js:769 TypeError: Oe.show is not a function
    at workbench.desktop.main.js:2695:19713
    at Array.map (<anonymous>)
    at ve.doSearch (workbench.desktop.main.js:2695:19702)
    at ve.refresh (workbench.desktop.main.js:2695:16890)
    at async Object.run (workbench.desktop.main.js:2699:65908)
    at async T.runAction (workbench.desktop.main.js:147:28220)
    at async T.run (workbench.desktop.main.js:147:28120)
    at async _.onClick (workbench.desktop.main.js:765:23902)
onDidChangeNotification @ workbench.desktop.main.js:769
(anonymous) @ workbench.desktop.main.js:769
_deliver @ workbench.desktop.main.js:87
_deliverQueue @ workbench.desktop.main.js:87
fire @ workbench.desktop.main.js:87
addNotification @ workbench.desktop.main.js:769
error @ workbench.desktop.main.js:1663
(anonymous) @ workbench.desktop.main.js:1681
_deliver @ workbench.desktop.main.js:87
_deliverQueue @ workbench.desktop.main.js:87
fire @ workbench.desktop.main.js:87
run @ workbench.desktop.main.js:147
await in run (async)
onClick @ workbench.desktop.main.js:765
(anonymous) @ workbench.desktop.main.js:245
```
