### ISSUE TITLE
vscodium-reh-linux-x64-1.85.0.23343.tar.gz GLIBCXX_3.4.26 not found

### ISSUE THREAD

**Issue by daugustus** [VSCodium/vscodium#1763]
vscodium-reh-linux-x64-1.85.0.23343 does not run on almalinux 8 with GLIBCXX_3.4.26 not found - previous versions worked

I do not use mscodium at all so I cannot confirm whether this works with MS

**To Reproduce**
1. download https://github.com/VSCodium/vscodium/releases/download/1.85.0.23343/vscodium-reh-linux-x64-1.85.0.23343.tar.gz
2. untar and run on almalinux 8
3. Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/node_modules/@vscode/spdlog/build/Release/spdlog.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/node_modules/@vscode/spdlog/index.js:3:35)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at r (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:3:98)
    at i.load (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:2:1637)
    at f.load (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:1:12350)
    at l (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:3:9338)
    at Object.errorback (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:3:9457)
    at f.triggerErrorback (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:1:12644)
    at /home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:1:12395
    at i.load (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:2:1654)
    at f.load (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:1:12350)
    at l (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:3:9338)
    at c._loadModule (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:3:9466)
    at c._resolve (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:4:452)
    at c.defineModule (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:3:5561)
    at c._relativeRequire (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:3:6185)
    at e (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:3:8516)
    at g (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/vs/server/node/server.main.js:109:56166)
    at new Promise (<anonymous>)
    at k (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/vs/server/node/server.main.js:109:56146)
    at y._createSpdLogLogger (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/vs/server/node/server.main.js:109:57366)
    at new y (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/vs/server/node/server.main.js:109:57180)
    at k.doCreateLogger (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/vs/server/node/server.main.js:109:58109)
    at k.createLogger (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/vs/server/node/server.main.js:109:8061)
    at Me (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/vs/server/node/server.main.js:169:109482)
    at ee (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/vs/server/node/server.main.js:177:7952)
    at async /home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:4:11437
    at async Server.<anonymous> (/home/dave.augustus/.vscodium-server/bin/00c993f9b9a2a07730235274df02f05bd76575f7/out/server-main.js:13:100) {
  code: 'ERR_DLOPEN_FAILED',
  phase: 'loading',
  moduleId: '@vscode/spdlog',
  neededBy: [ '===anonymous3===' ]
}

terminal only, no gui

Previous version of vscodium worked without issue on same platform

**Comment by daiyam** [comment]
duplicate #1760
