### ISSUE TITLE
HTML language features server crashing

### ISSUE THREAD

**Issue by cynanthropy** [VSCodium/vscodium#1813]
On startup, I get notifications telling me the HTML Language Features Server failed to initialise.

Here's the output:

`node:internal/modules/cjs/loader:1084
  const err = new Error(message);
              ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 4007 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1329945)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 6952 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1304163)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 8752 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1316613) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}

Node.js v18.17.1
[Error - 21:36:02] Server process exited with code 1.
[Error - 21:36:02] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:36:02] Connection to server got closed. Server will restart.
true
[Error - 21:36:02] HTML Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1084
  const err = new Error(message);
              ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 4007 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1329945)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 6952 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1304163)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 8752 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1316613) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}

Node.js v18.17.1
[Error - 21:36:03] Server process exited with code 1.
[Error - 21:36:03] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:36:03] Connection to server got closed. Server will restart.
true
[Error - 21:36:03] HTML Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1084
  const err = new Error(message);
              ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 4007 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1329945)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 6952 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1304163)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 8752 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1316613) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}

Node.js v18.17.1
[Error - 21:36:03] Server process exited with code 1.
[Error - 21:36:03] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:36:03] Connection to server got closed. Server will restart.
true
[Error - 21:36:03] HTML Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 21:36:03] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1084
  const err = new Error(message);
              ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 4007 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1329945)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 6952 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1304163)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 8752 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1316613) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}

Node.js v18.17.1
[Error - 21:36:04] Server process exited with code 1.
[Error - 21:36:04] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 21:36:04] Connection to server got closed. Server will restart.
true
[Error - 21:36:04] HTML Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 21:36:04] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1084
  const err = new Error(message);
              ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 4007 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1329945)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 6952 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1304163)
    at n (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1389066)
    at 8752 (/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1316613) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/codium/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}

Node.js v18.17.1
[Error - 21:36:04] Server process exited with code 1.
[Error - 21:36:04] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 21:36:04] The HTML Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 21:36:04] HTML Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 21:36:04] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
`

**Desktop:**
> Version: 1.86.2
> Release: 24053
> Commit: 480afc4fbb55849bd3c4cf651987191138f4d758
> Date: 2024-02-22T15:03:55.680Z
> Electron: 27.2.3
> ElectronBuildId: undefined
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Linux x64 6.1.0-18-amd64

**Comment by daiyam** [comment]
Please update to [1.86.2.24054](https://github.com/VSCodium/vscodium/releases/tag/1.86.2.24054), it's a known bug of `1.86.2.24054` https://github.com/VSCodium/vscodium/issues/1809

**Comment by Shadow-of-eagle** [comment]
How long will it roughtly take until the update will be avaiable via the apt package-manager?

**Comment by daiyam** [comment]
Please follow the updates there: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/98
