### ISSUE TITLE
Creating Files in External Drive Gives Errors

### ISSUE THREAD

**Issue by Godly-Avenger** [VSCodium/vscodium#1841]
**Describe the bug**
I do a lot of work in an external SSD that I use for school. Recently, when I'm trying to create a file in this external drive, it gives me an error (see screenshots below), but strangely still creates the file. This issue doesn't occur on other flash drives I've tested.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a folder in VSCodium from the external drive
2. Attempt to add a file by either clicking on the New File button or right-clicking and clicking New File
3. Enter in a file name
4. Click enter

**Expected behavior**
It should create the file without giving any error.

**Screenshots**
![image](https://github.com/VSCodium/vscodium/assets/74989919/e4b4f1ec-2d1c-4451-b62d-8ff24debd4f1)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture: x64
 - Version: 1.87.2
 - App Manager: Pacman/AUR
 - Sandboxed: no

**Additional context**
Some relevent output from `vscodium --verbose`
`[14327:0331/155857.417228:INFO:CONSOLE(651)] "%cTRACE color: #888 [File Watcher (parcel)] [ADDED] /run/media/godly_avenger/VentOwO/School/11th Grade (2022-2024)/Different Programming Languages/Assignments/Programs/C++/test1", source: vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js (651)
[14327:0331/155857.494489:INFO:CONSOLE(651)] "%cTRACE color: #888 [File Watcher (parcel)]  >> normalized [ADDED] /run/media/godly_avenger/VentOwO/School/11th Grade (2022-2024)/Different Programming Languages/Assignments/Programs/C++/test1", source: vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js (651)
[14327:0331/155857.729186:INFO:CONSOLE(651)] "%c  ERR color: #f33 Error: Unable to write file '/run/media/godly_avenger/VentOwO/School/11th Grade (2022-2024)/Different Programming Languages/Assignments/Programs/C++/test1' (Unknown (FileSystemError): Error: EFAULT: bad address in system call argument, write)", source: vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js (651)
[14327:0331/155857.730805:INFO:CONSOLE(785)] "Unable to write file '/run/media/godly_avenger/VentOwO/School/11th Grade (2022-2024)/Different Programming Languages/Assignments/Programs/C++/test1' (Unknown (FileSystemError): Error: EFAULT: bad address in system call argument, write)", source: vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js (785)
[14327:0331/155857.755919:INFO:CONSOLE(651)] "%c  ERR color: #f33 Unable to write file '/run/media/godly_avenger/VentOwO/School/11th Grade (2022-2024)/Different Programming Languages/Assignments/Programs/C++/test1' (Unknown (FileSystemError): Error: EFAULT: bad address in system call argument, write): Error: Unable to write file '/run/media/godly_avenger/VentOwO/School/11th Grade (2022-2024)/Different Programming Languages/Assignments/Programs/C++/test1' (Unknown (FileSystemError): Error: EFAULT: bad address in system call argument, write)
    at n.writeFile (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:653:23563)
    at async n.createFile (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:653:22510)
    at async Promise.all (index 0)
    at async Object.ne [as settled] (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:148:29797)
    at async i.doCreateFileOrFolder (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2423:69180)
    at async o.perform (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2429:26532)
    at async p.apply (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2429:29974)
    at async f._performFileEdits (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2429:32483)
    at async f.perform (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:2429:31987)`

**Comment by daiyam** [comment]
After a quick search, it seems to be an old issue with nodejs and external drive on linux (https://github.com/yarnpkg/yarn/issues/7152)

**Comment by Godly-Avenger** [comment]
Oh that's weird. Suppose I'll live with it. Thanks!

**Comment by daiyam** [comment]
I agree, it's weird
