### ISSUE TITLE
"[Extension Host] Fetch error: ReferenceError: fetch is not defined" with VSCodium, not VSCode

### ISSUE THREAD

**Issue by unclemusclez** [VSCodium/vscodium#2021]
In my experience this issue seems to be specific to VSCodium.
i just install the Microsoft Version of WSL targets and that didn't help the situation. Fetch is unable to initiate only when use WSL2

https://github.com/twinnydotdev/twinny
https://github.com/twinnydotdev/twinny/issues/242

```
  ERR [Extension Host] Fetch error: ReferenceError: fetch is not defined
	at streamResponse (/home/musclez/.vscodium-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:73722:22)
	at ChatService.streamResponse (/home/musclez/.vscodium-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:84891:12)
	at ChatService.streamChatCompletion (/home/musclez/.vscodium-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:85026:17)
workbench.desktop.main.js:97 [Extension Host] Fetch error: ReferenceError: fetch is not defined
	at streamResponse (/home/musclez/.vscodium-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:73722:22)
	at ChatService.streamResponse (/home/musclez/.vscodium-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:84891:12)
	at ChatService.streamChatCompletion (/home/musclez/.vscodium-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:85026:17)
```

**Comment by volgasezen** [comment]
I ran into this exact problem with the Jupyter extension, though this only happened in remote SSH connections. (Local installation was fine.)

My VSCodium version was 1.95.1.24307 (latest release). I solved this issue by going back to the previous version (1.94.2.24286). 

Although the node version did not change drastically between these releases, something lead to the fetch function within node.js not being accessible by remote machines.

Suffice to say I will not be updating VSCodium until this exact issue is resolved.

**Comment by volgasezen** [comment]
> `fetch` is a builtin function since `node-v18`. For compatibility, `reh` is still using `node-v16`. You can upgrade to `node-v20` by updating the `node` executable

I see, though this doesn't explain why downgrading a version helped avoid this issue. How would I check the version of node used by `reh`, or how would I update it?

**Comment by daiyam** [comment]
> I see, though this doesn't explain why downgrading a version helped avoid this issue.

Newer Node uses newer LibC not available on all distros.

> I installed node 20 via nvm, and it is seen in the terminal, but the extension host presumably sticks with the included node version.

In the `~/.vscodium-server/bin/<uuid>/`, there the binary file `node`. You will to update that file.

**Comment by daiyam** [comment]
I've opened a discussion #2126 about a possible solution.
