### ISSUE TITLE
HTTPError: Response code 404 when build for vscode-linux-x64-min-ci

### ISSUE THREAD

**Issue by xiaochao00** [VSCodium/vscodium#2028]
**Describe the bug**
Downloading electron: [====================================================================================================] 100% ETA: 0.0 seconds
[23:51:51] 'vscode-linux-x64-min-ci' errored after 12 s
[23:51:51] HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/root/vscodium/vscode/node_modules/got/dist/source/core/index.js:913:31)
    at Request._onResponse (/root/vscodium/vscode/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/root/vscodium/vscode/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:529:35)
    at ClientRequest.emit (node:domain:552:15)
    at origin.emit (/root/vscodium/vscode/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. ./build/build.sh

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu20.04

**Additional context**

**Comment by mcochranca** [comment]
***First***, thanks as an amateur I’ll just ask some surface troubleshooting questions to see if this may be addressed through configuration or network error. 
1. **Make sure that VSCodium is using up-to-date versions of Electron, got, and other dependencies. Run yarn upgrade or check for specific version requirements in the package.json or any lock files.**
2. VSCodium might be trying to download a resource from a location that has changed or been removed.
3. If the build script relies on a specific version of a package, and that version is no longer available or has been moved, this could cause a 404 error.


`If you identify an outdated or incorrect URL in the build script or configuration, updating it to the correct one should resolve the issue. Checking for updates to the VSCodium build process may already include a fix for this error though 
`

																																		— `  Good Luck`

**Comment by daiyam** [comment]
@mcochranca, I'm not sure where you got the issues but I never have those.

@xiaochao00, are you in China?

**Comment by xiaochao00** [comment]
yes I am in China

**Comment by daiyam** [comment]
> yes I am in China

I believe this why you are getting so much network error. You might need to reconfigure npm to use cnpm or taobao npm... I'm not sure.
