### ISSUE TITLE
node in vscodium-reh-linux-x64-1.96.0.24347.tar.gz is outdated

### ISSUE THREAD

**Issue by irauta** [VSCodium/vscodium#2158]
**Describe the bug**
The vscodium-server 1.96 is bundled with Node 16, but uses a library, undici, that doesn't support it.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
1. Connect to a remote Linux host (x64) with jeanp413's open-remote-ssh extension
2. Wait a moment
3. VSCodium says "Remote Extension host terminated unexpectedly 3 times within the last 5 minutes", and opening files is not possible.

**Expected behavior**
The remote connection should open.

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia
 - Architecture: Intel
 - Version: 1.96.0
 - App Manager: No (installed manually)
 - Sandboxed: No (nothing outside MacOS's own mechanisms)

**Additional context**

Excerpt from the remote host's log:
```
2024-12-13 12:15:24.102 [info] Extension host agent started.
2024-12-13 12:15:24.289 [info] [127.0.0.1][2cc30716][ManagementConnection] New connection established.
2024-12-13 12:15:24.315 [info] [127.0.0.1][3855d5de][ExtensionHostConnection] New connection established.
2024-12-13 12:15:24.659 [info] [127.0.0.1][3855d5de][ExtensionHostConnection] <627> Launched Extension Host Process.
2024-12-13 12:15:26.041 [info] [127.0.0.1][3855d5de][ExtensionHostConnection] <627><stderr> /home/ilkka/.vscodium-server/bin/e4195c69747f84abd56a7d1d82fd9fa236511d26/node_modules/undici/lib/web/fetch/response.js:527
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/home/ilkka/.vscodium-server/bin/e4195c69747f84abd56a7d1d82fd9fa236511d26/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/ilkka/.vscodium-server/bin/e4195c69747f84abd56a7d1d82fd9fa236511d26/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/ilkka/.vscodium-server/bin/e4195c69747f84abd56a7d1d82fd9fa236511d26/node_modules/undici/index.js:106:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/ilkka/.vscodium-server/bin/e4195c69747f84abd56a7d1d82fd9fa236511d26/node_modules/@vscode/proxy-agent/out/index.js:47:29)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async file:///home/ilkka/.vscodium-server/bin/e4195c69747f84abd56a7d1d82fd9fa236511d26/out/bootstrap-fork.js:17:1195

2024-12-13 12:15:26.100 [info] [127.0.0.1][3855d5de][ExtensionHostConnection] <627> Extension Host Process exited with code: 1, signal: null.
2024-12-13 12:15:26.108 [info] Cancelling previous shutdown timeout
```

As the log tells, the error happens in the [nodejs/undici](https://github.com/nodejs/undici) library. ReadableStream is being used without an import in the file mentioned in the stack trace, something that is supported only since Node.js 18 (see subheading "Web Streams API" of the Node v18.x release notes), but the node binary bundled in the .tar.gz reports version v16.20.2. The undici library is not present in an earlier version of the REH (when looking into the previous .vscodium-server/bin/*hash*/node_modules directory), so it seems to be a recently added dependency, explaining why the breakage only happened now.

**My workaround**

Inspired by #2157, I moved the node binary away and replaced it with a symlink to a newer version of node.

**Comment by daiyam** [comment]
Sorry, I'm behind my tasks... This week-end, I will try to implement the solution discussed at https://github.com/VSCodium/vscodium/discussions/2126

In the meantime, you can either replace the `node` executable with your own version or a symlink to your version.

**Comment by GitMensch** [comment]
one of my machine even has a different feature:

~~~
 /home/so/.vscodium-server/bin/e4195c69747f84abd56a7d1d82fd9fa236511d26/bin/codium-server --version
(node:297610) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/obs/opt/bin/codium/bin/e4195c69747f84abd56a7d1d82fd9fa236511d26/out/server-main.js:3
 *--------------------------------------------------------*/var xp=function(e,t){return xp=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(i,s){i.__proto__=s}||function(i,s){for(var r in s)Object.prototype.hasOwnProperty.call(s,r)&&(i[r]=s[r])},xp(e,t)};export function __extends(e,t){if(typeof t!="function"&&t!==null)throw new TypeError("Class extends value "+String(t)+" is not a constructor or null");xp(e,t);function i(){this.constructor=e}e.prototype=t===null?Object.create(t):(i.prototype=t.prototype,new i)}export var __assign=function(){return __assign=Object.assign||function(t){for(var i,s=1,r=arguments.length;s<r;s++){i=arguments[s];for(var n in i)Object.prototype.hasOwnProperty.call(i,n)&&(t[n]=i[n])}return t},__assign.apply(this,arguments)};export function __rest(e,t){var i={};for(var s in e)Object.prototype.hasOwnProperty.call(e,s)&&t.indexOf(s)<0&&(i[s]=e[s]);if(e!=null&&typeof Object.getOwnPropertySymbols=="function")for(var r=0,s=Object.getOwnPropertySymbols(e);r<s.length;r++)t.indexOf(s[r])<0&&Object.prototype.propertyIsEnumerable.call(e,s[r])&&(i[s[r]]=e[s[r]]);return i}export function __decorate(e,t,i,s){var r=arguments.length,n=r<3?t:s===null?s=Object.getOwnPropertyDescriptor(t,i):s,o;if(typeof Reflect=="object"&&typeof Reflect.decorate=="function")n=Reflect.decorate(e,t,i,s);else for(var a=e.length-1;a>=0;a--)(o=e[a])&&(n=(r<3?o(n):r>3?o(t,i,n):o(t,i))||n);return r>3&&n&&Object.defineProperty(t,i,n),n}export function __param(e,t){return function(i,s){t(i,s,e)}}export function __esDecorate(e,t,i,s,r,n){function o(S){if(S!==void 0&&typeof S!="function")throw new TypeError("Function expected");return S}for(var a=s.kind,c=a==="getter"?"get":a==="setter"?"set":"value",l=!t&&e?s.static?e:e.prototype:null,u=t||(l?Object.getOwnPropertyDescriptor(l,s.name):{}),h,d=!1,p=i.length-1;p>=0;p--){var m={};for(var v in s)m[v]=v==="access"?{}:s[v];for(var v in s.access)m.access[v]=s.access[v];m.addInitializer=function(S){if(d)throw new TypeError("Cannot add initializers after decoration has completed");n.push(o(S||null))};var _=(0,i[p])(a==="accessor"?{get:u.get,set:u.set}:u[c],m);if(a==="accessor"){if(_===void 0)continue;if(_===null||typeof _!="object")throw new TypeError("Object expected");(h=o(_.get))&&(u.get=h),(h=o(_.set))&&(u.set=h),(h=o(_.init))&&r.unshift(h)}else(h=o(_))&&(a==="field"?r.unshift(h):u[c]=h)}l&&Object.defineProperty(l,s.name,u),d=!0}export function __runInitializers(e,t,i){for(var s=arguments.length>2,r=0;r<t.length;r++)i=s?t[r].call(e,i):t[r].call(e);return s?i:void 0}export function __propKey(e){return typeof e=="symbol"?e:"".concat(e)}export function __setFunctionName(e,t,i){return typeof t=="symbol"&&(t=t.description?"[".concat(t.description,"]"):""),Object.defineProperty(e,"name",{configurable:!0,value:i?"".concat(i," ",t):t})}export function __metadata(e,t){if(typeof Reflect=="object"&&typeof Reflect.metadata=="function")return Reflect.metadata(e,t)}export function __awaiter(e,t,i,s){function r(n){return n instanceof i?n:new i(function(o){o(n)})}return new(i||(i=Promise))(function(n,o){function a(u){try{l(s.next(u))}catch(h){o(h)}}function c(u){try{l(s.throw(u))}catch(h){o(h)}}function l(u){u.done?n(u.value):r(u.value).then(a,c)}l((s=s.apply(e,t||[])).next())})}export function __generator(e,t){var i={label:0,sent:function(){if(n[0]&1)throw n[1];return n[1]},trys:[],ops:[]},s,r,n,o;return o={next:a(0),throw:a(1),return:a(2)},typeof Symbol=="function"&&(o[Symbol.iterator]=function(){return this}),o;function a(l){return function(u){return c([l,u])}}function c(l){if(s)throw new TypeError("Generator is already executing.");for(;o&&(o=0,l[0]&&(i=0)),i;)try{if(s=1,r&&(n=l[0]&2?r.return:l[0]?r.throw||((n=r.return)&&n.call(r),0):r.next)&&!(n=n.call(r,l[1])).done)return n;switch(r=0,n&&(l=[l[0]&2,n.value]),l[0]){case 0:case 1:n=l;break;case 4:return i.label++,{value:l[1],done:!1};case 5:i.label++,r=l[1],l=[0];continue;case 7:l=i.ops.pop(),i.trys.pop();continue;default:if(n=i.trys,!(n=n.length>0&&n[n.length-1])&&(l[0]===6||l[0]===2)){i=0;continue}if(l[0]===3&&(!n||l[1]>n[0]&&l[1]<n[3])){i.label=l[1];break}if(l[0]===6&&i.label<n[1]){i.label=n[1],n=l;break}if(n&&i.label<n[2]){i.label=n[2],i.ops.push(l);break}n[2]&&i.ops.pop(),i.trys.pop();continue}l=t.call(e,i)}catch(u){l=[6,u],r=0}finally{s=n=0}if(l[0]&5)throw l[1];return{value:l[0]?l[1]:void 0,done:!0}}}export var __createBinding=Object.create?function(e,t,i,s){s===void 0&&(s=i);var r=Object.getOwnPropertyDescriptor(t,i);(!r||("get"in r?!t.__esModule:r.writable||r.configurable))&&(r={enumerable:!0,get:function(){return t[i]}}),Object.defineProperty(e,s,r)}:function(e,t,i,s){s===void 0&&(s=i),e[s]=t[i]};export function __exportStar(e,t){for(var i in e)i!=="default"&&!Object.prototype.hasOwnProperty.call(t,i)&&__createBinding(t,e,i)}export function __values(e){var t=typeof Symbol=="function"&&Symbol.iterator,i=t&&e[t],s=0;if(i)return i.call(e);if(e&&typeof e.length=="number")return{next:function(){return e&&s>=e.length&&(e=void 0),{value:e&&e[s++],done:!e}}};throw new TypeError(t?"Object is not iterable.":"Symbol.iterator is not defined.")}export function __read(e,t){var i=typeof Symbol=="function"&&e[Symbol.iterator];if(!i)return e;var s=i.call(e),r,n=[],o;try{for(;(t===void 0||t-- >0)&&!(r=s.next()).done;)n.push(r.value)}catch(a){o={error:a}}finally{try{r&&!r.done&&(i=s.return)&&i.call(s)}finally{if(o)throw o.error}}return n}export function __spread(){for(var e=[],t=0;t<arguments.length;t++)e=e.concat(__read(arguments[t]));return e}export function __spreadArrays(){for(var e=0,t=0,i=arguments.length;t<i;t++)e+=arguments[t].length;for(var s=Array(e),r=0,t=0;t<i;t++)for(var n=arguments[t],o=0,a=n.length;o<a;o++,r++)s[r]=n[o];return s}export function __spreadArray(e,t,i){if(i||arguments.length===2)for(var s=0,r=t.length,n;s<r;s++)(n||!(s in t))&&(n||(n=Array.prototype.slice.call(t,0,s)),n[s]=t[s]);return e.concat(n||Array.prototype.slice.call(t))}export function __await(e){return this instanceof __await?(this.v=e,this):new __await(e)}export function __asyncGenerator(e,t,i){if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var s=i.apply(e,t||[]),r,n=[];return r={},a("next"),a("throw"),a("return",o),r[Symbol.asyncIterator]=function(){return this},r;function o(p){return function(m){return Promise.resolve(m).then(p,h)}}function a(p,m){s[p]&&(r[p]=function(v){return new Promise(function(_,S){n.push([p,v,_,S])>1||c(p,v)})},m&&(r[p]=m(r[p])))}function c(p,m){try{l(s[p](m))}catch(v){d(n[0][3],v)}}function l(p){p.value instanceof __await?Promise.resolve(p.value.v).then(u,h):d(n[0][2],p)}function u(p){c("next",p)}function h(p){c("throw",p)}function d(p,m){p(m),n.shift(),n.length&&c(n[0][0],n[0][1])}}export function __asyncDelegator(e){var t,i;return t={},s("next"),s("throw",function(r){throw r}),s("return"),t[Symbol.iterator]=function(){return this},t;function s(r,n){t[r]=e[r]?function(o){return(i=!i)?{value:__await(e[r](o)),done:!1}:n?n(o):o}:n}}export function __asyncValues(e){if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var t=e[Symbol.asyncIterator],i;return t?t.call(e):(e=typeof __values=="function"?__values(e):e[Symbol.iterator](),i={},s("next"),s("throw"),s("return"),i[Symbol.asyncIterator]=function(){return this},i);function s(n){i[n]=e[n]&&function(o){return new Promise(function(a,c){o=e[n](o),r(a,c,o.done,o.value)})}}function r(n,o,a,c){Promise.resolve(c).then(function(l){n({value:l,done:a})},o)}}export function __makeTemplateObject(e,t){return Object.defineProperty?Object.defineProperty(e,"raw",{value:t}):e.raw=t,e}var zI=Object.create?function(e,t){Object.defineProperty(e,"default",{enumerable:!0,value:t})}:function(e,t){e.default=t};export function __importStar(e){if(e&&e.__esModule)return e;var t={};if(e!=null)for(var i in e)i!=="default"&&Object.prototype.hasOwnProperty.call(e,i)&&__createBinding(t,e,i);return zI(t,e),t}export function __importDefault(e){return e&&e.__esModule?e:{default:e}}export function __classPrivateFieldGet(e,t,i,s){if(i==="a"&&!s)throw new TypeError("Private accessor was defined without a getter");if(typeof t=="function"?e!==t||!s:!t.has(e))throw new TypeError("Cannot read private member from an object whose class did not declare it");return i==="m"?s:i==="a"?s.call(e):s?s.value:t.get(e)}export function __classPrivateFieldSet(e,t,i,s,r){if(s==="m")throw new TypeError("Private method is not writable");if(s==="a"&&!r)throw new TypeError("Private accessor was defined without a setter");if(typeof t=="function"?e!==t||!r:!t.has(e))throw new TypeError("Cannot write private member to an object whose class did not declare it");return s==="a"?r.call(e,i):r?r.value=i:t.set(e,i),i}export function __classPrivateFieldIn(e,t){if(t===null||typeof t!="object"&&typeof t!="function")throw new TypeError("Cannot use 'in' operator on non-object");return typeof e=="function"?t===e:e.has(t)}export function __addDisposableResource(e,t,i){if(t!=null){if(typeof t!="object"&&typeof t!="function")throw new TypeError("Object expected.");var s,r;if(i){if(!Symbol.asyncDispose)throw new TypeError("Symbol.asyncDispose is not defined.");s=t[Symbol.asyncDispose]}if(s===void 0){if(!Symbol.dispose)throw new TypeError("Symbol.dispose is not defined.");s=t[Symbol.dispose],i&&(r=s)}if(typeof s!="function")throw new TypeError("Object not disposable.");r&&(s=function(){try{r.call(this)}catch(n){return Promise.reject(n)}}),e.stack.push({value:t,dispose:s,async:i})}else i&&e.stack.push({async:!0});return t}var qI=typeof SuppressedError=="function"?SuppressedError:function(e,t,i){var s=new Error(i);return s.name="SuppressedError",s.error=e,s.suppressed=t,s};export function __disposeResources(e){function t(s){e.error=e.hasError?new qI(s,e.error,"An error was suppressed during disposal."):s,e.hasError=!0}function i(){for(;e.stack.length;){var s=e.stack.pop();try{var r=s.dispose&&s.dispose.call(s.value);if(s.async)return Promise.resolve(r).then(i,function(n){return t(n),i()})}catch(n){t(n)}}if(e.hasError)throw e.error}return i()}export default{__extends,__assign,__rest,__decorate,__param,__metadata,__awaiter,__generator,__createBinding,__exportStar,__values,__read,__spread,__spreadArrays,__spreadArray,__await,__asyncGenerator,__asyncDelegator,__asyncValues,__makeTemplateObject,__importStar,__importDefault,__classPrivateFieldGet,__classPrivateFieldSet,__classPrivateFieldIn,__addDisposableResource,__disposeResources};var GI=Object.create,kp=Object.defineProperty,QI=Object.getOwnPropertyDescriptor,Pp=Object.getOwnPropertyNames,JI=Object.getPrototypeOf,XI=Object.prototype.hasOwnProperty,w=(e,t)=>function(){return e&&(t=(0,e[Pp(e)[0]])(e=0)),t},YI=(e,t)=>function(){return t||(0,e[Pp(e)[0]])((t={exports:{}}).exports,t),t.exports},ZI=(e,t)=>{for(var i in t)kp(e,i,{get:t[i],enumerable:!0})},KI=(e,t,i,s)=>{if(t&&typeof t=="object"||typeof t=="function")for(let r of Pp(t))!XI.call(e,r)&&r!==i&&kp(e,r,{get:()=>t[r],enumerable:!(s=QI(t,r))||s.enumerable});return e},Fw=(e,t,i)=>(i=e!=null?GI(JI(e)):{},KI(t||!e||!e.__esModule?kp(i,"default",{value:e,enumerable:!0}):i,e)),Uw=YI({"node_modules/minimist/index.js"(e,t){"use strict";function i(n,o){var a=n;o.slice(0,-1).forEach(function(l){a=a[l]||{}});var c=o[o.length-1];return c in a}function s(n){return typeof n=="number"||/^0x[0-9a-f]+$/i.test(n)?!0:/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(e[-+]?\d+)?$/.test(n)}function r(n,o){return o==="constructor"&&typeof n[o]=="function"||o==="__proto__"}t.exports=function(n,o){o||(o={});var a={bools:{},strings:{},unknownFn:null};typeof o.unknown=="function"&&(a.unknownFn=o.unknown),typeof o.boolean=="boolean"&&o.boolean?a.allBools=!0:[].concat(o.boolean).filter(Boolean).forEach(function(A){a.bools[A]=!0});var c={};function l(A){return c[A].some(function(le){return a.bools[le]})}Object.keys(o.alias||{}).forEach(function(A){c[A]=[].concat(o.alias[A]),c[A].forEach(function(le){c[le]=[A].concat(c[A].filter(function(ue){return le!==ue}))})}),[].concat(o.string).filter(Boolean).forEach(function(A){a.strings[A]=!0,c[A]&&[].concat(c[A]).forEach(function(le){a.strings[le]=!0})});var u=o.default||{},h={_:[]};function d(A,le){return a.allBools&&/^--[^=]+$/.test(le)||a.strings[A]||a.bools[A]||c[A]}function p(A,le,ue){for(var K=A,ht=0;ht<le.length-1;ht++){var T=le[ht];if(r(K,T))return;K[T]===void 0&&(K[T]={}),(K[T]===Object.prototype||K[T]===Number.prototype||K[T]===String.prototype)&&(K[T]={}),K[T]===Array.prototype&&(K[T]=[]),K=K[T]}var R=le[le.length-1];r(K,R)||((K===Object.prototype||K===Number.prototype||K===String.prototype)&&(K={}),K===Array.prototype&&(K=[]),K[R]===void 0||a.bools[R]||typeof K[R]=="boolean"?K[R]=ue:Array.isArray(K[R])?K[R].push(ue):K[R]=[K[R],ue])}function m(A,le,ue){if(!(ue&&a.unknownFn&&!d(A,ue)&&a.unknownFn(ue)===!1)){var K=!a.strings[A]&&s(le)?Number(le):le;p(h,A.split("."),K),(c[A]||[]).forEach(function(ht){p(h,ht.split("."),K)})}}Object.keys(a.bools).forEach(function(A){m(A,u[A]===void 0?!1:u[A])});var v=[];n.indexOf("--")!==-1&&(v=n.slice(n.indexOf("--")+1),n=n.slice(0,n.indexOf("--")));for(var _=0;_<n.length;_++){var S=n[_],E,C;if(/^--.+=/.test(S)){var I=S.match(/^--([^=]+)=([\s\S]*)$/);E=I[1];var L=I[2];a.bools[E]&&(L=L!=="false"),m(E,L,S)}else if(/^--no-.+/.test(S))E=S.match(/^--no-(.+)/)[1],m(E,!1,S);else if(/^--.+/.test(S))E=S.match(/^--(.+)/)[1],C=n[_+1],C!==void 0&&!/^(-|--)[^-]/.test(C)&&!a.bools[E]&&!a.allBools&&(!c[E]||!l(E))?(m(E,C,S),_+=1):/^(true|false)$/.test(C)?(m(E,C==="true",S),_+=1):m(E,a.strings[E]?"":!0,S);else if(/^-[^-]+/.test(S)){for(var q=S.slice(1,-1).split(""),te=!1,B=0;B<q.length;B++){if(C=S.slice(B+2),C==="-"){m(q[B],C,S);continue}if(/[A-Za-z]/.test(q[B])&&C[0]==="="){m(q[B],C.slice(1),S),te=!0;break}if(/[A-Za-z]/.test(q[B])&&/-?\d+(\.\d*)?(e-?\d+)?$/.test(C)){m(q[B],C,S),te=!0;break}if(q[B+1]&&q[B+1].match(/\W/)){m(q[B],S.slice(B+2),S),te=!0;break}else m(q[B],a.strings[q[B]]?"":!0,S)}E=S.slice(-1)[0],!te&&E!=="-"&&(n[_+1]&&!/^(-|--)[^-]/.test(n[_+1])&&!a.bools[E]&&(!c[E]||!l(E))?(m(E,n[_+1],S),_+=1):n[_+1]&&/^(true|false)$/.test(n[_+1])?(m(E,n[_+1]==="true",S),_+=1):m(E,a.strings[E]?"":!0,S))}else if((!a.unknownFn||a.unknownFn(S)!==!1)&&h._.push(a.strings._||!s(S)?S:Number(S)),o.stopEarly){h._.push.apply(h._,n.slice(_+1));break}}return Object.keys(u).forEach(function(A){i(h,A.split("."))||(p(h,A.split("."),u[A]),(c[A]||[]).forEach(function(le){p(h,le.split("."),u[A])}))}),o["--"]?h["--"]=v.slice():v.forEach(function(A){h._.push(A)}),h}}});function Ip(e){const t=[];typeof e=="number"&&t.push("code/timeOrigin",e);function i(r,n){t.push(r,n?.startTime??Date.now())}function s(){const r=[];for(let n=0;n<t.length;n+=2)r.push({name:t[n],startTime:t[n+1]});return r}return{mark:i,getMarks:s}}function eC(){if(typeof performance=="object"&&typeof performance.mark=="function"&&!performance.nodeTiming)return typeof performance.timeOrigin!="number"&&!performance.timing?Ip():{mark(e,t){performance.mark(e,t)},getMarks(){let e=performance.timeOrigin;typeof e!="number"&&(e=performance.timing.navigationStart||performance.timing.redirectStart||performance.timing.fetchStart);const t=[{name:"code/timeOrigin",startTime:Math.round(e)}];for(const i of performance.getEntriesByType("mark"))t.push({name:i.name,startTime:Math.round(e+i.startTime)});return t}};if(typeof process=="object"){const e=performance?.timeOrigin;return Ip(e)}else return console.trace("perf-util loaded in UNKNOWN environment"),Ip()}function tC(e){return e.MonacoPerformanceMarks||(e.MonacoPerformanceMarks=eC()),e.MonacoPerformanceMarks}var Cp,Pt,$w,Qs=w({"out-build/vs/base/common/performance.js"(){"use strict";Cp=tC(globalThis),Pt=Cp.mark,$w=Cp.getMarks}});import*as gs from"path";import*as ms from"fs";async function Ww({userLocale:e,osLocale:t,userDataPath:i,commit:s,nlsMetadataPath:r}){if(Pt("code/willGenerateNls"),process.env.VSCODE_DEV||e==="pseudo"||e.startsWith("en")||!s||!i)return Ta(e,t,r);try{const n=await iC(i);if(!n)return Ta(e,t,r);const o=sC(n,e);if(!o)return Ta(e,t,r);const a=n[o],c=a?.translations?.vscode;if(!a||typeof a.hash!="string"||!a.translations||typeof c!="string"||!await Dp(c))return Ta(e,t,r);const l=`${a.hash}.${o}`,u=gs.join(i,"clp",l),h=gs.join(u,s),d=gs.join(h,"nls.messages.json"),p=gs.join(u,"tcf.json"),m=gs.join(u,"corrupted.info");await Dp(m)&&await ms.promises.rm(u,{recursive:!0,force:!0,maxRetries:3});const v={userLocale:e,osLocale:t,resolvedLanguage:o,defaultMessagesFile:gs.join(r,"nls.messages.json"),languagePack:{translationsConfigFile:p,messagesFile:d,corruptMarkerFile:m},locale:e,availableLanguages:{"*":o},_languagePackId:l,_languagePackSupport:!0,_translationsConfigFile:p,_cacheRoot:u,_resolvedLanguagePackCoreLocation:h,_corruptedFile:m};if(await Dp(h))return rC(h).catch(()=>{}),Pt("code/didGenerateNls"),v;const[,_,S,E]=await Promise.all([ms.promises.mkdir(h,{recursive:!0}),JSON.parse(await ms.promises.readFile(gs.join(r,"nls.keys.json"),"utf-8")),JSON.parse(await ms.promises.readFile(gs.join(r,"nls.messages.json"),"utf-8")),JSON.parse(await ms.promises.readFile(c,"utf-8"))]),C=[];let I=0;for(const[L,q]of _){const te=E.contents[L];for(const B of q)C.push(te?.[B]||S[I]),I++}return await Promise.all([ms.promises.writeFile(d,JSON.stringify(C),"utf-8"),ms.promises.writeFile(p,JSON.stringify(a.translations),"utf-8")]),Pt("code/didGenerateNls"),v}catch(n){console.error("Generating translation files failed.",n)}return Ta(e,t,r)}async function iC(e){const t=gs.join(e,"languagepacks.json");try{return JSON.parse(await ms.promises.readFile(t,"utf-8"))}catch{return}}function sC(e,t){try{for(;t;){if(e[t])return t;const i=t.lastIndexOf("-");if(i>0)t=t.substring(0,i);else return}}catch(i){console.error("Resolving language pack configuration failed.",i)}}function Ta(e,t,i){return Pt("code/didGenerateNls"),{userLocale:e,osLocale:t,resolvedLanguage:"en",defaultMessagesFile:gs.join(i,"nls.messages.json"),locale:e,availableLanguages:{}}}async function Dp(e){try{return await ms.promises.access(e),!0}catch{return!1}}function rC(e){const t=new Date;return ms.promises.utimes(e,t,t)}var Hw=w({"out-build/vs/base/node/nls.js"(){"use strict";Qs()}});function Vw(e){Na.setUnexpectedErrorHandler(e)}function jw(e){if(!e||typeof e!="object")return!1;const t=e;return t.code==="EPIPE"&&t.syscall?.toUpperCase()==="WRITE"}function nu(e){Na.onUnexpectedError(e)}function zt(e){Pr(e)||Na.onUnexpectedError(e)}function Pr(e){return e instanceof It?!0:e instanceof Error&&e.name===Ma&&e.message===Ma}function Bw(){const e=new Error(Ma);return e.name=e.message,e}function Ne(e){return e?new Error(`Illegal argument: ${e}`):new Error("Illegal argument")}function zw(e){return e?new Error(`Illegal state: ${e}`):new Error("Illegal state")}function me(e){return e?e.message?e.message:e.stack?e.stack.split(`
                                                                                                                                                                                                                                                                              ^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
~~~

... even when I manually replace node by 20.10 (but only on RHEL8 ?!?)

When replacing the node 16 binary with node 20.10 on RHEL9 that works there.

**Comment by daiyam** [comment]
Yes, RHEL8 has been a problem since October.
I moved the RPM to `el9` with https://github.com/VSCodium/vscodium/commit/33a2643e1b9ba230ccb02a290e55ad1d0b0ab1df

**Comment by daiyam** [comment]
I'm ok to move it back to `el8` if a PR can be provided ;)

**Comment by jeffcutsinger** [comment]
Instructions to downgrade for people using the repository on debian-based distributions:

```
sudo apt remove codium
sudo tee /etc/apt/preferences.d/block-codium-1.96.0.24347.pref >/dev/null <<EOF 
Package: codium
Pin: version 1.96.0.24347
Pin-Priority: -999
EOF
curl -fsSL -O https://github.com/VSCodium/vscodium/releases/download/1.95.3.24321/codium_1.95.3.24321_amd64.deb
sudo dpkg -i codium_1.95.3.24321_amd64.deb
```

**Comment by daiyam** [comment]
Can you test the version [`1.96.0.24352`](https://github.com/VSCodium/vscodium/releases/tag/1.96.0.24352)? Thx

**Comment by GitMensch** [comment]
Note: I've recognized a change in product.json below `"extensionEnabledApiProposals"` between this version and the previous 1.96.0.24347 (just got my attention because of no entry in the release changelog)

```diff
-   "GitHub.copilot": ["inlineCompletionsAdditions", "interactive", "terminalDataWriteEvent"],
-   "GitHub.copilot-nightly": ["inlineCompletionsAdditions", "interactive", "terminalDataWriteEvent"],
-   "GitHub.copilot-chat": ["interactive", "terminalDataWriteEvent", "terminalExecuteCommandEvent", "terminalSelection", "terminalQuickFixProvider", "chatProvider", "chatParticipantAdditions", "defaultChatParticipant", "embeddings", "chatVariableResolver", "mappedEditsProvider", "aiRelatedInformation", "codeActionAI", "findTextInFiles", "textSearchProvider", "textSearchProvider2", "activeComment", "commentReveal", "contribSourceControlInputBoxMenu", "contribCommentEditorActionsMenu", "contribCommentThreadAdditionalMenu", "contribCommentsViewThreadMenus", "newSymbolNamesProvider", "findFiles2", "extensionsAny", "authLearnMore", "testObserver", "aiTextSearchProvider", "documentFiltersExclusive", "chatParticipantPrivate", "contribDebugCreateConfiguration", "inlineEdit"],
-   "GitHub.copilot-nes": ["inlineEdit"],
+   "GitHub.copilot": ["inlineCompletionsAdditions"],
+   "GitHub.copilot-nightly": ["inlineCompletionsAdditions"],
+   "GitHub.copilot-chat": ["interactive", "terminalDataWriteEvent", "terminalExecuteCommandEvent", "terminalSelection", "terminalQuickFixProvider", "chatParticipantAdditions", "defaultChatParticipant", "embeddings", "chatEditing", "chatVariableResolver", "chatProvider", "mappedEditsProvider", "aiRelatedInformation", "codeActionAI", "findTextInFiles", "textSearchProvider", "textSearchProvider2", "activeComment", "commentReveal", "contribSourceControlInputBoxMenu", "contribCommentEditorActionsMenu", "contribCommentThreadAdditionalMenu", "contribCommentsViewThreadMenus", "newSymbolNamesProvider", "findFiles2", "extensionsAny", "authLearnMore", "testObserver", "aiTextSearchProvider", "documentFiltersExclusive", "chatParticipantPrivate", "contribDebugCreateConfiguration", "inlineEdit"],
```

But I can report that REH works fine in current Debian, RHEL8+RHEL9 again.

**Comment by irauta** [comment]
Just upgraded to 1.96.0.24352, and it's working as expected for me too. Thank you!
