### ISSUE TITLE
ARM packages.

### ISSUE THREAD

**Issue by JL2210** [VSCodium/vscodium#6]
I'm helping with a GPL package manager for Chromebooks, called Chromebrew. It would really help if you could also create i686 and ARM tarballs. Thank you.

**Comment by sam0x17** [comment]
vscode on chromebook would be amazing

**Comment by JL2210** [comment]
@sam0x17 We already have it for i686 and x86_64.

**Comment by stripedpajamas** [comment]
@JL2210 there aren't any ARM tarballs for Microsoft's Visual Studio Code, are there? I didn't see any on the website. Our best case scenario right now is offering everything Microsoft offers on their website.

**Comment by JL2210** [comment]
Well, then, could you offer 32-bit x86 packages? Microsoft offers those on their website.

**Comment by stripedpajamas** [comment]
@JL2210 Yes! As noted on the README, we are looking for PRs to do just that.

**Comment by JL2210** [comment]
OK. Also, a note on the README. 32-bit x86 and x32 are two entirely different things. X32 is a 32-bit pointer ABI for x86_64 and 32-bit x86 is purely 32-bit.

**Comment by stripedpajamas** [comment]
@JL2210 good catch. How does [this](https://github.com/VSCodium/vscodium/pull/30) look?

**Comment by JL2210** [comment]
You might add a note about X32 in there, too. (Link)[https://en.wikipedia.org/wiki/X32_ABI]

**Comment by stripedpajamas** [comment]
Can you propose what that note would say?

**Comment by JL2210** [comment]
I'm not entirely sure. You could say `The 32-bit x86, ARM and X32 architectures are currently not supported.`
I highly doubt that Microsoft will ever support the X32 ABI in VSCode.

**Comment by JL2210** [comment]
Good idea. I will probably create a PR for 32-bit x86 by the end of the day. Just a few `for` statements.

**Comment by JL2210** [comment]
How's [this](https://github.com/VSCodium/vscodium/pull/31)?

**Comment by JL2210** [comment]
Great. One objective of this is done. Any idea how we could create ARM packages?

**Comment by Metaception** [comment]
Assuming I am understanding this issue correctly, this repo is dedicated to this: https://code.headmelted.com/

**Comment by JL2210** [comment]
@Metaception: We tried that in Chromebrew. Those are Debian binaries, and they only work on Raspberry Pis and Crouton. 
@stripedpajamas: It should just be as easy as adding more lines to the scripts for ARM and adding support to `.travis.yml`.

**Comment by JL2210** [comment]
One more step!

**Comment by stripedpajamas** [comment]
@435vic I think there is a lot of set up that has to be done in the build environment to produce good arm binaries. Take a look at https://github.com/headmelted/codebuilds and https://github.com/headmelted/cobbler (which produces the files for https://code.headmelted.com). 

I will take a stab at setting up something similar in this repo but I have no way of testing the binaries. If you can do that (or @JL2210) before we merge anything in that would be great.

**Comment by JL2210** [comment]
Just a quick comment, could you switch the Travis builds to Debian? I know that Ubuntu messes with their GTK libs.

**Comment by JL2210** [comment]
Also, I'd be free to test them. I'd better fire up another Gentoo chroot on my desktop.

**Comment by stripedpajamas** [comment]
@435vic @JL2210 I just rebuilt arm64 after setting the npm_config_arch (as per the suggestion in #42) -- can either of you see if these binaries work?

[tar](https://github.com/stripedpajamas/vscodium/releases/download/1.28.1/VSCode-linux-arm64-1.28.1.tar.gz)
[deb](https://github.com/stripedpajamas/vscodium/releases/download/1.28.1/vscodium_1.28.1-1539349591_arm64.deb)

**Comment by 435vic** [comment]
Tar isn't working:
![image](https://user-images.githubusercontent.com/13788817/46878916-3d67ae80-ce0a-11e8-866d-0f5579cef64e.png)
![image](https://user-images.githubusercontent.com/13788817/46878620-620f5680-ce09-11e8-98da-fa77b17f3bf6.png)
Neither is the deb:
![image](https://user-images.githubusercontent.com/13788817/46878963-5ff9c780-ce0a-11e8-86bf-f21f2af28450.png)

I think I'm just gonna build from source...

**Comment by JL2210** [comment]
@435vic, could you please try this on a regular AArch64 computer, not a Chromebook? I imagine it would work if you tried it there.

**Comment by JL2210** [comment]
I noticed `penguin` is your hostname. I got it from there.

**Comment by stripedpajamas** [comment]
What is in zeit/hyper#26 ? All I see are comments about fonts.

**Comment by JL2210** [comment]
See edited comment. Sorry :/

**Comment by JL2210** [comment]
@435vic Can you send me the output of just `./vscodium` when in that directory? Usually, the executable itself gives us more hints than the wrapper script.

**Comment by 435vic** [comment]
Sure.
```[795:1012/200627.161752:ERROR:gl_surface_glx.cc(408)] glxQueryVersion failed
[795:1012/200627.162034:ERROR:gl_initializer_x11.cc(153)] GLSurfaceGLX::InitializeOneOff failed.
[795:1012/200627.169572:ERROR:gpu_child_thread.cc(252)] Exiting GPU process due to errors during initialization
[763:1012/200627.189790:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
Error: /home/435victorjavier/vscodiumtar/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:15:808)
    at bindings (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Object.<anonymous> (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/spdlog/index.js:21:3)
    at Module.i._compile (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:31:146)
    at Object.t.createSpdLogService (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:231:561)
    at /home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:534:447
    at Object.v [as _notify] (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:96:807)
    at Object.enter (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:100:85)
    at n.Class.derive._creator._run (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:101:932)
    at n.Class.derive._creator._completed (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:101:373)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: /home/435victorjavier/vscodiumtar/resources/app/node_modules.asar.unpacked/native-keymap/build/Release/keymapping.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:15:808)
    at NativeBinding._init (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/native-keymap/index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/native-keymap/index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/native-keymap/index.js:61:18)
    at e.onDidChangeKeyboardLayout (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:318:939)
    at t.registerListeners (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:519:645)
    at t (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:516:967)
    at t.create (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:62:770)
    at e._createInstance (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:213:703)
    at e.createInstance (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:212:959)
    at /home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:534:501
    at Object.v [as _notify] (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:96:807)
    at Object.enter (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:100:85)
    at n.Class.derive._creator._run (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:101:932)
    at n.Class.derive._creator._completed (/home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-main/main.js:101:373)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[main 8:06:27 PM] Starting VS Code
[main 8:06:27 PM] from: /home/435victorjavier/vscodiumtar/resources/app
[main 8:06:27 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  trace: false }
[main 8:06:27 PM] Resolving machine identifier...
[main 8:06:27 PM] Resolved machine identifier: 8dd7ce575121be5a4bc18923af27954d1175d4dccf036072690e72157116395a
[main 8:06:27 PM] update#ctor - updates are disabled
[main 8:06:27 PM] windowsManager#open
[763:1012/200628.500215:ERROR:bus.cc(395)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[763:1012/200630.652672:INFO:CONSOLE(7)] "Loading "node-pty" failed", source: /home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js (7)
[763:1012/200630.652816:INFO:CONSOLE(7)] "Detail: ", source: /home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js (7)
[763:1012/200630.655009:INFO:CONSOLE(7)] "Error: /home/435victorjavier/vscodiumtar/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:15:808)
    at Object.<anonymous> (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:21:11)
    at Object.<anonymous> (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:252:3)
    at Module.t._initNodeRequire.i._compile (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:15:808)
    at Object.<anonymous> (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/node-pty/lib/index.js:13:20)
    at Object.<anonymous> (/home/435victorjavier/vscodiumtar/resources/app/node_modules.asar/node-pty/lib/index.js:51:3)
    at Module.t._initNodeRequire.i._compile (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at i (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:31:146)
    at t.load (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:16:408)
    at e.load (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:13:813)
    at i (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:28:217)
    at Object.errorback (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:28:338)
    at e.triggerErrorback (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:14:176)
    at /home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:13:883
    at ReadFileContext.callback (/home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js:16:619)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)", source: /home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js (7)
[763:1012/200630.655324:INFO:CONSOLE(7)] "Here are the modules that depend on it:", source: /home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js (7)
[763:1012/200630.655513:INFO:CONSOLE(7)] "vs/workbench/parts/terminal/node/terminalProcess", source: /home/435victorjavier/vscodiumtar/resources/app/out/vs/loader.js (7)
[763:1012/200631.529437:ERROR:bus.cc(395)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[763:1012/200632.481929:INFO:CONSOLE(176)] "Error: /home/435victorjavier/vscodiumtar/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory", source: file:///home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (176)
[763:1012/200632.487934:INFO:CONSOLE(176)] "Error: /home/435victorjavier/vscodiumtar/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory", source: file:///home/435victorjavier/vscodiumtar/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (176)
```

**Comment by JL2210** [comment]
@435vic, could you try `dbus-launch ./vscodium`?

**Comment by 435vic** [comment]
Still not working.
![image](https://user-images.githubusercontent.com/13788817/47224827-1ec16480-d382-11e8-9d20-18a5020ec85e.png)
```
435victorjavier@vicoquincis:~/VSCode-linux-arm64$ dbus-launch ./vscodium
Error: /home/435victorjavier/VSCode-linux-arm64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/loader.js:15:808)
    at bindings (/home/435victorjavier/VSCode-linux-arm64/resources/app/node_modules.asar/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/435victorjavier/VSCode-linux-arm64/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Object.<anonymous> (/home/435victorjavier/VSCode-linux-arm64/resources/app/node_modules.asar/spdlog/index.js:21:3)
    at Module.i._compile (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/loader.js:16:65)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/loader.js:31:146)
    at Object.t.createSpdLogService (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:231:561)
    at /home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:534:447
    at Object.v [as _notify] (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:96:807)
    at Object.enter (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:100:85)
    at n.Class.derive._creator._run (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:101:932)
    at n.Class.derive._creator._completed (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:101:373)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: /home/435victorjavier/VSCode-linux-arm64/resources/app/node_modules.asar.unpacked/native-keymap/build/Release/keymapping.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/loader.js:15:808)
    at NativeBinding._init (/home/435victorjavier/VSCode-linux-arm64/resources/app/node_modules.asar/native-keymap/index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (/home/435victorjavier/VSCode-linux-arm64/resources/app/node_modules.asar/native-keymap/index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (/home/435victorjavier/VSCode-linux-arm64/resources/app/node_modules.asar/native-keymap/index.js:61:18)
    at e.onDidChangeKeyboardLayout (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:318:939)
    at t.registerListeners (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:519:645)
    at t (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:516:967)
    at t.create (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:62:770)
    at e._createInstance (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:213:703)
    at e.createInstance (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:212:959)
    at /home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:534:501
    at Object.v [as _notify] (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:96:807)
    at Object.enter (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:100:85)
    at n.Class.derive._creator._run (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:101:932)
    at n.Class.derive._creator._completed (/home/435victorjavier/VSCode-linux-arm64/resources/app/out/vs/code/electron-main/main.js:101:373)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[main 9:32:01 AM] update#ctor - updates are disabled
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell```

**Comment by JL2210** [comment]
@stripedpajamas Could you update the `yarn` version used? It could be an issue with that. Just install `yarn` from backports.

**Comment by sam0x17** [comment]
Shouldn't the package be using its own self-contained version of node/yarn/etc?

**Comment by stripedpajamas** [comment]
Will work on getting that updated @JL2210

**Comment by 435vic** [comment]
By the way, I set up a [test repository](https://github.com/435vic/vscode-arm64) that updates yarn to 1.10.1 and builds vanilla vscode and that still didn't work, so I refiled [the issue](https://github.com/Microsoft/vscode/issues/61623) for this test repository instead of vscodium on the official microsoft repository. I hope it will soon be looked into. If you want to look at the Travis CI page, [here](https://travis-ci.com/435vic/vscode-arm64) it is.

**Comment by JL2210** [comment]
@435vic @stripedpajamas Could it be a combination of #42 and an older node version? Also, when in the unpacked VSCodium directory, please run `./bin/vscodium`

**Comment by JL2210** [comment]
https://github.com/Microsoft/node-spdlog and https://github.com/Microsoft/node-native-keymap are possible dependencies.

**Comment by stripedpajamas** [comment]
@JL2210 I believe we're using the latest supported node version (supported by vscode). Their docs say `>= 8.12.0, < 9.0.0`. 

In re: yarn, since @435vic tried building with 1.10.1 and got the same thing, I want to hear more from Microsoft.

I'm also a little confused... are we not able to somehow replicate how https://code.headmelted.com is getting these builds going?

**Comment by JL2210** [comment]
@stripedpajamas @435vic Sorry. I meant a newer Yarn version. https://code.headmelted.com/ only works in Crouton, but we want it to work in Crostini and in devmode Chrome OS, which isn't the same because they have different X displays than Crouton. Microsoft doesn't even build binaries for ARM right now. Why would they have a want or a need to support us?

**Comment by JL2210** [comment]
Can you give a link?

**Comment by JL2210** [comment]
@435vic I found the exact problem in VSCodium, look at this code:
```
  elif [[ $BUILDARCH == "arm64" ]]; then
    # Use the default C / C++ compilers,
    # because some makefiles default to CC:=gcc:
    export CC=/usr/bin/cc
    export CXX=/usr/bin/c++
  fi
```

**Comment by 1138-4EB** [comment]
Is there any update on this? @JL2210 where is that snippet extracted from?

**Comment by JL2210** [comment]
I'm not sure how progress is going on this, as I've distanced myself from
this conversation. You'd have to ask one of the maintainers to see if arm
support works yet.

**Comment by stripedpajamas** [comment]
ARM builds have not worked so far. As the architecture is not supported by MS with Visual Studio Code, this is low priority. Any contributions to this end are appreciated.

**Comment by JL2210** [comment]
I don't think Ubuntu works on ARM very well. A better long-term solution
would be switching to Debian.

I believe the code snippet was from install_deps.sh.

**Comment by JL2210** [comment]
Their wiki mentions ARM: https://github.com/Microsoft/vscode/wiki/Cross-Compiling-for-Debian-Based-Linux

**Comment by 1138-4EB** [comment]
@JL2210, I was considering to use QEMU and docker (see https://github.com/dbhi/qus) as an alternative to cross-compilation. Incidentaly, that seems to be the suggested approach in the ref to posted. However, on the one hand, I am not sure if dbhi/qus would work on the Azure pipeline that this repos uses. On the other hand, I found https://github.com/headmelted/codebuilds

**Comment by stripedpajamas** [comment]
As a side note, the Linux builds run in Travis, not Azure pipelines.

**Comment by bUKaneer** [comment]
Not sure if this helps but I've been trying to build vscode from source on my pi4 because current packages only work up to version 1.29. However I believe the solution to getting a successful build on or up to 1.41 is detailed in this post on [stackoverflow](https://stackoverflow.com/a/58440967/1370442).

**Comment by dimkr** [comment]
Could this be related to the use of pkg-config in https://github.com/microsoft/node-native-keymap/blob/master/binding.gyp? Does it respect PKG_CONFIG_PATH, etc'?

**Comment by dimkr** [comment]
Almost there! node-native-keymap compiles for arm64 now, https://travis-ci.org/dimkr/vscodium/jobs/622718293#L2250

**Comment by dimkr** [comment]
Please see #302

**Comment by stripedpajamas** [comment]
Thanks so much for working on this @dimkr 

I think we're in a place where this issue can be closed. If there are issues with the new arm builds let's open a fresh issue regarding those.
