### ISSUE TITLE
VSCodium 1.60 crash on Fedora 35 (pre-release)

### ISSUE THREAD

**Issue by patrickdung** [VSCodium/vscodium#852]
It should run fine on Fedora 34 (VSCodium 1.59/1.60). After upgrade it crash on start.
I also try to use version 1.59 and the result is the same.

```
$ codium --verbose --disable-gpu
[1498290:0921/035252.377370:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for swiftshader
[1498290:0921/035252.377500:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[1498256:0921/035252.391784:ERROR:gpu_process_host.cc(1003)] GPU process exited unexpectedly: exit_code=159
[1498256:0921/035252.391802:WARNING:gpu_process_host.cc(1317)] The GPU process has crashed 1 time(s)
[1498321:0921/035252.442715:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for swiftshader
[1498321:0921/035252.442811:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[1498256:0921/035252.457194:ERROR:gpu_process_host.cc(1003)] GPU process exited unexpectedly: exit_code=159
[1498256:0921/035252.457209:WARNING:gpu_process_host.cc(1317)] The GPU process has crashed 2 time(s)
[main 2021-09-20T19:52:52.463Z] Starting VS Code
[main 2021-09-20T19:52:52.464Z] from: /usr/share/codium/resources/app
[main 2021-09-20T19:52:52.464Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': true,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/user1/.config/VSCodium/logs/20210921T035252'
}
[main 2021-09-20T19:52:52.465Z] Resolving machine identifier...
[main 2021-09-20T19:52:52.466Z] Resolved machine identifier: eaa22abaec50a96215a87e342ff1a70c3bae334448124b32dba67d56127ecb42
[main 2021-09-20T19:52:52.466Z] Main->SharedProcess#connect
[1498326:0921/035252.476648:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for swiftshader
[1498326:0921/035252.476766:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[main 2021-09-20T19:52:52.489Z] StorageMainService: creating global storage
[main 2021-09-20T19:52:52.489Z] lifecycle (main): phase changed (value: 2)
[main 2021-09-20T19:52:52.490Z] windowsManager#open
[main 2021-09-20T19:52:52.490Z] windowsManager#open pathsToOpen [
  {
    backupPath: '/home/user1/.config/VSCodium/Backups/1632094705302',
    remoteAuthority: undefined
  }
]
[main 2021-09-20T19:52:52.492Z] IPC Object URL: Registered new channel vscode:2da2534e-6431-4f85-a7a4-2e5da7bc13b1.
[main 2021-09-20T19:52:52.492Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 1, y: 128, width: 1918, height: 927 }
[1498256:0921/035252.492853:ERROR:gpu_process_host.cc(1003)] GPU process exited unexpectedly: exit_code=159
[1498256:0921/035252.492865:WARNING:gpu_process_host.cc(1317)] The GPU process has crashed 3 time(s)
[main 2021-09-20T19:52:52.492Z] window#validateWindowState: 1 monitor working area { x: 0, y: 27, width: 1920, height: 951 }
[main 2021-09-20T19:52:52.492Z] window#ctor: using window state { mode: 1, x: 1, y: 128, width: 1918, height: 927 }
[main 2021-09-20T19:52:52.557Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-09-20T19:52:52.558Z] lifecycle (main): phase changed (value: 3)
[main 2021-09-20T19:52:52.559Z] update#setState idle
[1498344:0921/035252.559527:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for disabled
[1498344:0921/035252.559629:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[main 2021-09-20T19:52:52.559Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[1498256:0921/035252.571200:ERROR:gpu_process_host.cc(1003)] GPU process exited unexpectedly: exit_code=159
[1498256:0921/035252.571221:WARNING:gpu_process_host.cc(1317)] The GPU process has crashed 4 time(s)
[1498360:0921/035252.593472:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for disabled
[1498360:0921/035252.593549:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[1498256:0921/035252.604167:ERROR:gpu_process_host.cc(1003)] GPU process exited unexpectedly: exit_code=159
[1498256:0921/035252.604187:WARNING:gpu_process_host.cc(1317)] The GPU process has crashed 5 time(s)
[1498366:0921/035252.608906:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for disabled
[1498366:0921/035252.608984:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[1498256:0921/035252.619525:ERROR:gpu_process_host.cc(1003)] GPU process exited unexpectedly: exit_code=159
[1498256:0921/035252.619537:WARNING:gpu_process_host.cc(1317)] The GPU process has crashed 6 time(s)
[1498256:0921/035252.619547:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
```

**Comment by morphy2k** [comment]
I'm using the Fedora 35 beta and it crashes here too.
The Microsoft build works without issues.

```TEXT
$ codium 
internal/modules/cjs/loader.js:1125
    throw err;
    ^

SyntaxError: /usr/share/codium/resources/app/product.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1122:22)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/share/codium/resources/app/out/cli.js:1:133)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by patrickdung** [comment]
Strange. I saw Markus replied to this thread. It's in email notification by GitHub.
But I do not saw the reply in here..

**Comment by daiyam** [comment]
@patrickdung Yes, I saw it too. But his issue wasn't related to yours (only that it happens on Fedora). And maybe, he has fixed the JSON file and removed his comment.

**Comment by patrickdung** [comment]
Here's the backtrace.
```
Core was generated by `/usr/share/codium/codium'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading source file /usr/src/debug/glibc-2.34-6.fc35.x86_64/nptl/pthread_kill.c...
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
[Current thread is 1 (Thread 0x7f600c58ddc0 (LWP 967340))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f60103138c3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:80
#2  0x00007f60102c66b6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f60102b07d3 in __GI_abort () at abort.c:79
#4  0x00007f6010307a27 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f60104442b4 "%s")
    at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007f6010307aaa in __GI___libc_fatal (message=0x7f60104467f8 "The futex facility returned an unexpected error code.\n")
    at ../sysdeps/posix/libc_fatal.c:164
#6  0x00007f60103192d5 in futex_fatal_error () at ../sysdeps/nptl/futex-internal.h:87
#7  futex_wake (private=<optimized out>, processes_to_wake=1, futex_word=<optimized out>) at ../sysdeps/nptl/futex-internal.h:225
#8  __new_sem_post (sem=<optimized out>) at sem_post.c:57
#9  0x000056139af4b0e7 in uv_sem_post ()
#10 0x000056139b06f987 in  ()
#11 0x000026f927805400 in  ()
#12 0x000026f927927430 in  ()
#13 0x00007fff593166e0 in  ()
#14 0x000056139b09eeee in  ()
#15 0x00005613a129a208 in  ()
#16 0x000026f927811240 in  ()
#17 0x00007fff59316700 in  ()
#18 0x000056139b000a71 in  ()
#19 0x000026f927811240 in  ()
#20 0x0000000000000000 in  ()
```

**Comment by patrickdung** [comment]
Workaround:
https://github.com/microsoft/vscode/issues/134255#issuecomment-932387897
```
code --disable-gpu-sandbox
```

**Comment by patrickdung** [comment]
The problem does not occur on codium 1.61.
