### ISSUE TITLE
The outline tree is empty with Python files

### ISSUE THREAD

**Issue by gerroon** [VSCodium/vscodium#893]
**Describe the bug**
Hi

The outline is totally empty with Python files. I do not use any other language so I do not know if it works for other languages. This was working fine couple versions ago since I use it regularly. I upgraded to to 1.61.2 now it is gone. I am not sure which version I had it working but I have been using the outline for couple years no problem. I did not change my settings for quite sometime as well.

**Please confirm that this problem is VSCodium-specific**
- [x] I do no use Vscode

**Please confirm that the issue/resolution isn't already documented**
- [x]  I could not find a similar bug

**To Reproduce**
1. Open a Python file
2. Make sure you have the Python extension enabled
3. Open the outline window

**Expected behavior**
It should liest all the functions and classes properly instead of showing an empty pane.

**Screenshots**

![VSCodium_o31LzcXjLU](https://user-images.githubusercontent.com/8519469/139509339-f9725d1b-0c96-46e1-b1c2-7f41a03c8d44.jpg)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Architecture x64
- Python extension v2021.10.1365161279
- VsCodium 1.61.2

I see this  in the log window

Log

```
Symbol(ILanguageServerActivator) - named: Jedi 
: Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi 

    at C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:153537
    at m (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:153834)
    at e (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:154325)
    at Object.t.plan (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:154988)
    at C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:151572a
    at e._get (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:151481)
    at e.getTagged (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:150284)
    at e.getNamed (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:150376)
    at a.get (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:78:515280)
    at P.createRefCountedServer (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:201054)
    at P.activate (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:198188)
    at async Promise.all (index 5)
    at y.activateWorkspace (C:\VSCODE\.vscode-oss\extensions\ms-python.python-2021.10.1365161279\out\client\extension.js:52:193521)
```

Python
```
python -m pip install jedi

Requirement already satisfied: jedi in c:\python39\lib\site-packages (0.18.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\python39\lib\site-packages (from jedi) (0.8.2)

```

**Comment by gerroon** [comment]
I removed Pylance and it is back. Not sure how Pylance got installed. Maybe the Python extention installs it.

**Comment by carlinmack** [comment]
Pylance is also not working for me, doesn't even suggest defined variables to me nevermind properties on libraries etc

**Comment by daiyam** [comment]
Please read my comment on #892
